/* tslint:disable */
/* eslint-disable */
/**
 * Steamworks Web API
 * This is an OpenAPI specification for the Steamworks Web API. For more details on how to use this tool, check out the <a href=\"https://github.com/ceva24/openapi-steamworks-web-api/blob/main/README.md\">README</a>.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * IAuthenticationServiceApi - axios parameter creator
 */
export const IAuthenticationServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IAuthenticationServiceBeginAuthSessionViaCredentialsV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {string} [deviceFriendlyName] (Required)
         * @param {string} [accountName] (Required)
         * @param {string} [encryptedPassword] (Required) password, RSA encrypted client side
         * @param {number} [encryptionTimestamp] (Required) timestamp to map to a key - STime
         * @param {boolean} [rememberLogin] (Required) deprecated
         * @param {string} [platformType] (Required)
         * @param {string} [persistence] whether we are requesting a persistent or an ephemeral session
         * @param {string} [websiteId] (EMachineAuthWebDomain) identifier of client requesting auth
         * @param {string} [deviceDetails] (Required) User-supplied details about the device attempting to sign in
         * @param {string} [guardData] (Required) steam guard data for client login
         * @param {number} [language] (Required)
         * @param {number} [qosLevel] [ENetQOSLevel] client-specified priority for this auth attempt
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iAuthenticationServiceBeginAuthSessionViaCredentialsV1Post: async (inputJson?: string, format?: IAuthenticationServiceBeginAuthSessionViaCredentialsV1PostFormatEnum, deviceFriendlyName?: string, accountName?: string, encryptedPassword?: string, encryptionTimestamp?: number, rememberLogin?: boolean, platformType?: string, persistence?: string, websiteId?: string, deviceDetails?: string, guardData?: string, language?: number, qosLevel?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IAuthenticationService/BeginAuthSessionViaCredentials/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            if (deviceFriendlyName !== undefined) { 
                localVarFormParams.set('device_friendly_name', deviceFriendlyName as any);
            }

            if (accountName !== undefined) { 
                localVarFormParams.set('account_name', accountName as any);
            }

            if (encryptedPassword !== undefined) { 
                localVarFormParams.set('encrypted_password', encryptedPassword as any);
            }

            if (encryptionTimestamp !== undefined) { 
                localVarFormParams.set('encryption_timestamp', encryptionTimestamp as any);
            }

            if (rememberLogin !== undefined) { 
                localVarFormParams.set('remember_login', rememberLogin as any);
            }

            if (platformType !== undefined) { 
                localVarFormParams.set('platform_type', platformType as any);
            }

            if (persistence !== undefined) { 
                localVarFormParams.set('persistence', persistence as any);
            }

            if (websiteId !== undefined) { 
                localVarFormParams.set('website_id', websiteId as any);
            }

            if (deviceDetails !== undefined) { 
                localVarFormParams.set('device_details', deviceDetails as any);
            }

            if (guardData !== undefined) { 
                localVarFormParams.set('guard_data', guardData as any);
            }

            if (language !== undefined) { 
                localVarFormParams.set('language', language as any);
            }

            if (qosLevel !== undefined) { 
                localVarFormParams.set('qos_level', qosLevel as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IAuthenticationServiceBeginAuthSessionViaQRV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {string} [deviceFriendlyName] (Required)
         * @param {string} [platformType] (Required)
         * @param {string} [deviceDetails] (Required) User-supplied details about the device attempting to sign in
         * @param {string} [websiteId] (EMachineAuthWebDomain) identifier of client requesting auth
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iAuthenticationServiceBeginAuthSessionViaQRV1Post: async (inputJson?: string, format?: IAuthenticationServiceBeginAuthSessionViaQRV1PostFormatEnum, deviceFriendlyName?: string, platformType?: string, deviceDetails?: string, websiteId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IAuthenticationService/BeginAuthSessionViaQR/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            if (deviceFriendlyName !== undefined) { 
                localVarFormParams.set('device_friendly_name', deviceFriendlyName as any);
            }

            if (platformType !== undefined) { 
                localVarFormParams.set('platform_type', platformType as any);
            }

            if (deviceDetails !== undefined) { 
                localVarFormParams.set('device_details', deviceDetails as any);
            }

            if (websiteId !== undefined) { 
                localVarFormParams.set('website_id', websiteId as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IAuthenticationServiceGetAuthSessionInfoV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [clientId] (Required) client ID from scanned QR Code, used for routing
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iAuthenticationServiceGetAuthSessionInfoV1Post: async (inputJson?: string, format?: IAuthenticationServiceGetAuthSessionInfoV1PostFormatEnum, clientId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IAuthenticationService/GetAuthSessionInfo/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            if (clientId !== undefined) { 
                localVarFormParams.set('client_id', clientId as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IAuthenticationServiceGetAuthSessionRiskInfoV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [clientId] (Required) client ID from scanned QR Code, used for routing
         * @param {number} [language] (Required) language for optimistic localization of geoloc data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iAuthenticationServiceGetAuthSessionRiskInfoV1Post: async (inputJson?: string, format?: IAuthenticationServiceGetAuthSessionRiskInfoV1PostFormatEnum, clientId?: number, language?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IAuthenticationService/GetAuthSessionRiskInfo/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            if (clientId !== undefined) { 
                localVarFormParams.set('client_id', clientId as any);
            }

            if (language !== undefined) { 
                localVarFormParams.set('language', language as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [accountName] (Required) user-provided account name to get an RSA key for
         * @param {string} [inputJson] An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IAuthenticationServiceGetPasswordRSAPublicKeyV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iAuthenticationServiceGetPasswordRSAPublicKeyV1Get: async (accountName?: string, inputJson?: string, format?: IAuthenticationServiceGetPasswordRSAPublicKeyV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IAuthenticationService/GetPasswordRSAPublicKey/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (accountName !== undefined) {
                localVarQueryParameter['account_name'] = accountName;
            }

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IAuthenticationServiceNotifyRiskQuizResultsV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [clientId] (Required) client ID for the auth session, used for routing
         * @param {string} [results] (Required) Whether or not the user correctly answered each risk quiz question
         * @param {string} [selectedAction] (Required) The action being taken selected by the user during the quiz
         * @param {boolean} [didConfirmLogin] (Required) Whether or not the user went on to confirm the login or not in the case of a passed quiz
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iAuthenticationServiceNotifyRiskQuizResultsV1Post: async (inputJson?: string, format?: IAuthenticationServiceNotifyRiskQuizResultsV1PostFormatEnum, clientId?: number, results?: string, selectedAction?: string, didConfirmLogin?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IAuthenticationService/NotifyRiskQuizResults/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            if (clientId !== undefined) { 
                localVarFormParams.set('client_id', clientId as any);
            }

            if (results !== undefined) { 
                localVarFormParams.set('results', results as any);
            }

            if (selectedAction !== undefined) { 
                localVarFormParams.set('selected_action', selectedAction as any);
            }

            if (didConfirmLogin !== undefined) { 
                localVarFormParams.set('did_confirm_login', didConfirmLogin as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IAuthenticationServicePollAuthSessionStatusV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [clientId] (Required)
         * @param {string} [requestId] (Required)
         * @param {number} [tokenToRevoke] (Required) If this is set to a token owned by this user, that token will be retired
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iAuthenticationServicePollAuthSessionStatusV1Post: async (inputJson?: string, format?: IAuthenticationServicePollAuthSessionStatusV1PostFormatEnum, clientId?: number, requestId?: string, tokenToRevoke?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IAuthenticationService/PollAuthSessionStatus/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            if (clientId !== undefined) { 
                localVarFormParams.set('client_id', clientId as any);
            }

            if (requestId !== undefined) { 
                localVarFormParams.set('request_id', requestId as any);
            }

            if (tokenToRevoke !== undefined) { 
                localVarFormParams.set('token_to_revoke', tokenToRevoke as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [version] (Required) version field
         * @param {number} [clientId] (Required) pending client ID, from scanned QR Code
         * @param {number} [steamid] (Required) user who wants to login
         * @param {string} [signature] (Required) HMAC digest over {version,client_id,steamid} via user\\\&#39;s private key
         * @param {boolean} [confirm] Whether to confirm the login (true) or deny the login (false)
         * @param {string} [persistence] whether we are requesting a persistent or an ephemeral session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1Post: async (inputJson?: string, format?: IAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1PostFormatEnum, version?: number, clientId?: number, steamid?: number, signature?: string, confirm?: boolean, persistence?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IAuthenticationService/UpdateAuthSessionWithMobileConfirmation/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            if (version !== undefined) { 
                localVarFormParams.set('version', version as any);
            }

            if (clientId !== undefined) { 
                localVarFormParams.set('client_id', clientId as any);
            }

            if (steamid !== undefined) { 
                localVarFormParams.set('steamid', steamid as any);
            }

            if (signature !== undefined) { 
                localVarFormParams.set('signature', signature as any);
            }

            if (confirm !== undefined) { 
                localVarFormParams.set('confirm', confirm as any);
            }

            if (persistence !== undefined) { 
                localVarFormParams.set('persistence', persistence as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [clientId] (Required) pending client ID, from initialized session
         * @param {number} [steamid] (Required) user who wants to login
         * @param {string} [code] (Required) confirmation code
         * @param {string} [codeType] (Required) type of confirmation code
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1Post: async (inputJson?: string, format?: IAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1PostFormatEnum, clientId?: number, steamid?: number, code?: string, codeType?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IAuthenticationService/UpdateAuthSessionWithSteamGuardCode/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            if (clientId !== undefined) { 
                localVarFormParams.set('client_id', clientId as any);
            }

            if (steamid !== undefined) { 
                localVarFormParams.set('steamid', steamid as any);
            }

            if (code !== undefined) { 
                localVarFormParams.set('code', code as any);
            }

            if (codeType !== undefined) { 
                localVarFormParams.set('code_type', codeType as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IAuthenticationServiceApi - functional programming interface
 */
export const IAuthenticationServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IAuthenticationServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IAuthenticationServiceBeginAuthSessionViaCredentialsV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {string} [deviceFriendlyName] (Required)
         * @param {string} [accountName] (Required)
         * @param {string} [encryptedPassword] (Required) password, RSA encrypted client side
         * @param {number} [encryptionTimestamp] (Required) timestamp to map to a key - STime
         * @param {boolean} [rememberLogin] (Required) deprecated
         * @param {string} [platformType] (Required)
         * @param {string} [persistence] whether we are requesting a persistent or an ephemeral session
         * @param {string} [websiteId] (EMachineAuthWebDomain) identifier of client requesting auth
         * @param {string} [deviceDetails] (Required) User-supplied details about the device attempting to sign in
         * @param {string} [guardData] (Required) steam guard data for client login
         * @param {number} [language] (Required)
         * @param {number} [qosLevel] [ENetQOSLevel] client-specified priority for this auth attempt
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iAuthenticationServiceBeginAuthSessionViaCredentialsV1Post(inputJson?: string, format?: IAuthenticationServiceBeginAuthSessionViaCredentialsV1PostFormatEnum, deviceFriendlyName?: string, accountName?: string, encryptedPassword?: string, encryptionTimestamp?: number, rememberLogin?: boolean, platformType?: string, persistence?: string, websiteId?: string, deviceDetails?: string, guardData?: string, language?: number, qosLevel?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iAuthenticationServiceBeginAuthSessionViaCredentialsV1Post(inputJson, format, deviceFriendlyName, accountName, encryptedPassword, encryptionTimestamp, rememberLogin, platformType, persistence, websiteId, deviceDetails, guardData, language, qosLevel, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IAuthenticationServiceApi.iAuthenticationServiceBeginAuthSessionViaCredentialsV1Post']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IAuthenticationServiceBeginAuthSessionViaQRV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {string} [deviceFriendlyName] (Required)
         * @param {string} [platformType] (Required)
         * @param {string} [deviceDetails] (Required) User-supplied details about the device attempting to sign in
         * @param {string} [websiteId] (EMachineAuthWebDomain) identifier of client requesting auth
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iAuthenticationServiceBeginAuthSessionViaQRV1Post(inputJson?: string, format?: IAuthenticationServiceBeginAuthSessionViaQRV1PostFormatEnum, deviceFriendlyName?: string, platformType?: string, deviceDetails?: string, websiteId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iAuthenticationServiceBeginAuthSessionViaQRV1Post(inputJson, format, deviceFriendlyName, platformType, deviceDetails, websiteId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IAuthenticationServiceApi.iAuthenticationServiceBeginAuthSessionViaQRV1Post']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IAuthenticationServiceGetAuthSessionInfoV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [clientId] (Required) client ID from scanned QR Code, used for routing
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iAuthenticationServiceGetAuthSessionInfoV1Post(inputJson?: string, format?: IAuthenticationServiceGetAuthSessionInfoV1PostFormatEnum, clientId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iAuthenticationServiceGetAuthSessionInfoV1Post(inputJson, format, clientId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IAuthenticationServiceApi.iAuthenticationServiceGetAuthSessionInfoV1Post']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IAuthenticationServiceGetAuthSessionRiskInfoV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [clientId] (Required) client ID from scanned QR Code, used for routing
         * @param {number} [language] (Required) language for optimistic localization of geoloc data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iAuthenticationServiceGetAuthSessionRiskInfoV1Post(inputJson?: string, format?: IAuthenticationServiceGetAuthSessionRiskInfoV1PostFormatEnum, clientId?: number, language?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iAuthenticationServiceGetAuthSessionRiskInfoV1Post(inputJson, format, clientId, language, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IAuthenticationServiceApi.iAuthenticationServiceGetAuthSessionRiskInfoV1Post']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [accountName] (Required) user-provided account name to get an RSA key for
         * @param {string} [inputJson] An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IAuthenticationServiceGetPasswordRSAPublicKeyV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iAuthenticationServiceGetPasswordRSAPublicKeyV1Get(accountName?: string, inputJson?: string, format?: IAuthenticationServiceGetPasswordRSAPublicKeyV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iAuthenticationServiceGetPasswordRSAPublicKeyV1Get(accountName, inputJson, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IAuthenticationServiceApi.iAuthenticationServiceGetPasswordRSAPublicKeyV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IAuthenticationServiceNotifyRiskQuizResultsV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [clientId] (Required) client ID for the auth session, used for routing
         * @param {string} [results] (Required) Whether or not the user correctly answered each risk quiz question
         * @param {string} [selectedAction] (Required) The action being taken selected by the user during the quiz
         * @param {boolean} [didConfirmLogin] (Required) Whether or not the user went on to confirm the login or not in the case of a passed quiz
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iAuthenticationServiceNotifyRiskQuizResultsV1Post(inputJson?: string, format?: IAuthenticationServiceNotifyRiskQuizResultsV1PostFormatEnum, clientId?: number, results?: string, selectedAction?: string, didConfirmLogin?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iAuthenticationServiceNotifyRiskQuizResultsV1Post(inputJson, format, clientId, results, selectedAction, didConfirmLogin, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IAuthenticationServiceApi.iAuthenticationServiceNotifyRiskQuizResultsV1Post']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IAuthenticationServicePollAuthSessionStatusV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [clientId] (Required)
         * @param {string} [requestId] (Required)
         * @param {number} [tokenToRevoke] (Required) If this is set to a token owned by this user, that token will be retired
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iAuthenticationServicePollAuthSessionStatusV1Post(inputJson?: string, format?: IAuthenticationServicePollAuthSessionStatusV1PostFormatEnum, clientId?: number, requestId?: string, tokenToRevoke?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iAuthenticationServicePollAuthSessionStatusV1Post(inputJson, format, clientId, requestId, tokenToRevoke, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IAuthenticationServiceApi.iAuthenticationServicePollAuthSessionStatusV1Post']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [version] (Required) version field
         * @param {number} [clientId] (Required) pending client ID, from scanned QR Code
         * @param {number} [steamid] (Required) user who wants to login
         * @param {string} [signature] (Required) HMAC digest over {version,client_id,steamid} via user\\\&#39;s private key
         * @param {boolean} [confirm] Whether to confirm the login (true) or deny the login (false)
         * @param {string} [persistence] whether we are requesting a persistent or an ephemeral session
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1Post(inputJson?: string, format?: IAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1PostFormatEnum, version?: number, clientId?: number, steamid?: number, signature?: string, confirm?: boolean, persistence?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1Post(inputJson, format, version, clientId, steamid, signature, confirm, persistence, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IAuthenticationServiceApi.iAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1Post']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [clientId] (Required) pending client ID, from initialized session
         * @param {number} [steamid] (Required) user who wants to login
         * @param {string} [code] (Required) confirmation code
         * @param {string} [codeType] (Required) type of confirmation code
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1Post(inputJson?: string, format?: IAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1PostFormatEnum, clientId?: number, steamid?: number, code?: string, codeType?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1Post(inputJson, format, clientId, steamid, code, codeType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IAuthenticationServiceApi.iAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1Post']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * IAuthenticationServiceApi - factory interface
 */
export const IAuthenticationServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IAuthenticationServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {IAuthenticationServiceApiIAuthenticationServiceBeginAuthSessionViaCredentialsV1PostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iAuthenticationServiceBeginAuthSessionViaCredentialsV1Post(requestParameters: IAuthenticationServiceApiIAuthenticationServiceBeginAuthSessionViaCredentialsV1PostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iAuthenticationServiceBeginAuthSessionViaCredentialsV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.deviceFriendlyName, requestParameters.accountName, requestParameters.encryptedPassword, requestParameters.encryptionTimestamp, requestParameters.rememberLogin, requestParameters.platformType, requestParameters.persistence, requestParameters.websiteId, requestParameters.deviceDetails, requestParameters.guardData, requestParameters.language, requestParameters.qosLevel, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IAuthenticationServiceApiIAuthenticationServiceBeginAuthSessionViaQRV1PostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iAuthenticationServiceBeginAuthSessionViaQRV1Post(requestParameters: IAuthenticationServiceApiIAuthenticationServiceBeginAuthSessionViaQRV1PostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iAuthenticationServiceBeginAuthSessionViaQRV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.deviceFriendlyName, requestParameters.platformType, requestParameters.deviceDetails, requestParameters.websiteId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IAuthenticationServiceApiIAuthenticationServiceGetAuthSessionInfoV1PostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iAuthenticationServiceGetAuthSessionInfoV1Post(requestParameters: IAuthenticationServiceApiIAuthenticationServiceGetAuthSessionInfoV1PostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iAuthenticationServiceGetAuthSessionInfoV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.clientId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IAuthenticationServiceApiIAuthenticationServiceGetAuthSessionRiskInfoV1PostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iAuthenticationServiceGetAuthSessionRiskInfoV1Post(requestParameters: IAuthenticationServiceApiIAuthenticationServiceGetAuthSessionRiskInfoV1PostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iAuthenticationServiceGetAuthSessionRiskInfoV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.clientId, requestParameters.language, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IAuthenticationServiceApiIAuthenticationServiceGetPasswordRSAPublicKeyV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iAuthenticationServiceGetPasswordRSAPublicKeyV1Get(requestParameters: IAuthenticationServiceApiIAuthenticationServiceGetPasswordRSAPublicKeyV1GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iAuthenticationServiceGetPasswordRSAPublicKeyV1Get(requestParameters.accountName, requestParameters.inputJson, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IAuthenticationServiceApiIAuthenticationServiceNotifyRiskQuizResultsV1PostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iAuthenticationServiceNotifyRiskQuizResultsV1Post(requestParameters: IAuthenticationServiceApiIAuthenticationServiceNotifyRiskQuizResultsV1PostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iAuthenticationServiceNotifyRiskQuizResultsV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.clientId, requestParameters.results, requestParameters.selectedAction, requestParameters.didConfirmLogin, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IAuthenticationServiceApiIAuthenticationServicePollAuthSessionStatusV1PostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iAuthenticationServicePollAuthSessionStatusV1Post(requestParameters: IAuthenticationServiceApiIAuthenticationServicePollAuthSessionStatusV1PostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iAuthenticationServicePollAuthSessionStatusV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.clientId, requestParameters.requestId, requestParameters.tokenToRevoke, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IAuthenticationServiceApiIAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1PostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1Post(requestParameters: IAuthenticationServiceApiIAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1PostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.version, requestParameters.clientId, requestParameters.steamid, requestParameters.signature, requestParameters.confirm, requestParameters.persistence, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IAuthenticationServiceApiIAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1PostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1Post(requestParameters: IAuthenticationServiceApiIAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1PostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.clientId, requestParameters.steamid, requestParameters.code, requestParameters.codeType, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for iAuthenticationServiceBeginAuthSessionViaCredentialsV1Post operation in IAuthenticationServiceApi.
 */
export interface IAuthenticationServiceApiIAuthenticationServiceBeginAuthSessionViaCredentialsV1PostRequest {
    /**
     * An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IAuthenticationServiceBeginAuthSessionViaCredentialsV1PostFormatEnum

    /**
     * (Required)
     */
    readonly deviceFriendlyName?: string

    /**
     * (Required)
     */
    readonly accountName?: string

    /**
     * (Required) password, RSA encrypted client side
     */
    readonly encryptedPassword?: string

    /**
     * (Required) timestamp to map to a key - STime
     */
    readonly encryptionTimestamp?: number

    /**
     * (Required) deprecated
     */
    readonly rememberLogin?: boolean

    /**
     * (Required)
     */
    readonly platformType?: string

    /**
     * whether we are requesting a persistent or an ephemeral session
     */
    readonly persistence?: string

    /**
     * (EMachineAuthWebDomain) identifier of client requesting auth
     */
    readonly websiteId?: string

    /**
     * (Required) User-supplied details about the device attempting to sign in
     */
    readonly deviceDetails?: string

    /**
     * (Required) steam guard data for client login
     */
    readonly guardData?: string

    /**
     * (Required)
     */
    readonly language?: number

    /**
     * [ENetQOSLevel] client-specified priority for this auth attempt
     */
    readonly qosLevel?: number
}

/**
 * Request parameters for iAuthenticationServiceBeginAuthSessionViaQRV1Post operation in IAuthenticationServiceApi.
 */
export interface IAuthenticationServiceApiIAuthenticationServiceBeginAuthSessionViaQRV1PostRequest {
    /**
     * An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IAuthenticationServiceBeginAuthSessionViaQRV1PostFormatEnum

    /**
     * (Required)
     */
    readonly deviceFriendlyName?: string

    /**
     * (Required)
     */
    readonly platformType?: string

    /**
     * (Required) User-supplied details about the device attempting to sign in
     */
    readonly deviceDetails?: string

    /**
     * (EMachineAuthWebDomain) identifier of client requesting auth
     */
    readonly websiteId?: string
}

/**
 * Request parameters for iAuthenticationServiceGetAuthSessionInfoV1Post operation in IAuthenticationServiceApi.
 */
export interface IAuthenticationServiceApiIAuthenticationServiceGetAuthSessionInfoV1PostRequest {
    /**
     * An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IAuthenticationServiceGetAuthSessionInfoV1PostFormatEnum

    /**
     * (Required) client ID from scanned QR Code, used for routing
     */
    readonly clientId?: number
}

/**
 * Request parameters for iAuthenticationServiceGetAuthSessionRiskInfoV1Post operation in IAuthenticationServiceApi.
 */
export interface IAuthenticationServiceApiIAuthenticationServiceGetAuthSessionRiskInfoV1PostRequest {
    /**
     * An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IAuthenticationServiceGetAuthSessionRiskInfoV1PostFormatEnum

    /**
     * (Required) client ID from scanned QR Code, used for routing
     */
    readonly clientId?: number

    /**
     * (Required) language for optimistic localization of geoloc data
     */
    readonly language?: number
}

/**
 * Request parameters for iAuthenticationServiceGetPasswordRSAPublicKeyV1Get operation in IAuthenticationServiceApi.
 */
export interface IAuthenticationServiceApiIAuthenticationServiceGetPasswordRSAPublicKeyV1GetRequest {
    /**
     * (Required) user-provided account name to get an RSA key for
     */
    readonly accountName?: string

    /**
     * An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IAuthenticationServiceGetPasswordRSAPublicKeyV1GetFormatEnum
}

/**
 * Request parameters for iAuthenticationServiceNotifyRiskQuizResultsV1Post operation in IAuthenticationServiceApi.
 */
export interface IAuthenticationServiceApiIAuthenticationServiceNotifyRiskQuizResultsV1PostRequest {
    /**
     * An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IAuthenticationServiceNotifyRiskQuizResultsV1PostFormatEnum

    /**
     * (Required) client ID for the auth session, used for routing
     */
    readonly clientId?: number

    /**
     * (Required) Whether or not the user correctly answered each risk quiz question
     */
    readonly results?: string

    /**
     * (Required) The action being taken selected by the user during the quiz
     */
    readonly selectedAction?: string

    /**
     * (Required) Whether or not the user went on to confirm the login or not in the case of a passed quiz
     */
    readonly didConfirmLogin?: boolean
}

/**
 * Request parameters for iAuthenticationServicePollAuthSessionStatusV1Post operation in IAuthenticationServiceApi.
 */
export interface IAuthenticationServiceApiIAuthenticationServicePollAuthSessionStatusV1PostRequest {
    /**
     * An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IAuthenticationServicePollAuthSessionStatusV1PostFormatEnum

    /**
     * (Required)
     */
    readonly clientId?: number

    /**
     * (Required)
     */
    readonly requestId?: string

    /**
     * (Required) If this is set to a token owned by this user, that token will be retired
     */
    readonly tokenToRevoke?: number
}

/**
 * Request parameters for iAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1Post operation in IAuthenticationServiceApi.
 */
export interface IAuthenticationServiceApiIAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1PostRequest {
    /**
     * An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1PostFormatEnum

    /**
     * (Required) version field
     */
    readonly version?: number

    /**
     * (Required) pending client ID, from scanned QR Code
     */
    readonly clientId?: number

    /**
     * (Required) user who wants to login
     */
    readonly steamid?: number

    /**
     * (Required) HMAC digest over {version,client_id,steamid} via user\\\&#39;s private key
     */
    readonly signature?: string

    /**
     * Whether to confirm the login (true) or deny the login (false)
     */
    readonly confirm?: boolean

    /**
     * whether we are requesting a persistent or an ephemeral session
     */
    readonly persistence?: string
}

/**
 * Request parameters for iAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1Post operation in IAuthenticationServiceApi.
 */
export interface IAuthenticationServiceApiIAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1PostRequest {
    /**
     * An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1PostFormatEnum

    /**
     * (Required) pending client ID, from initialized session
     */
    readonly clientId?: number

    /**
     * (Required) user who wants to login
     */
    readonly steamid?: number

    /**
     * (Required) confirmation code
     */
    readonly code?: string

    /**
     * (Required) type of confirmation code
     */
    readonly codeType?: string
}

/**
 * IAuthenticationServiceApi - object-oriented interface
 */
export class IAuthenticationServiceApi extends BaseAPI {
    /**
     * 
     * @param {IAuthenticationServiceApiIAuthenticationServiceBeginAuthSessionViaCredentialsV1PostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iAuthenticationServiceBeginAuthSessionViaCredentialsV1Post(requestParameters: IAuthenticationServiceApiIAuthenticationServiceBeginAuthSessionViaCredentialsV1PostRequest = {}, options?: RawAxiosRequestConfig) {
        return IAuthenticationServiceApiFp(this.configuration).iAuthenticationServiceBeginAuthSessionViaCredentialsV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.deviceFriendlyName, requestParameters.accountName, requestParameters.encryptedPassword, requestParameters.encryptionTimestamp, requestParameters.rememberLogin, requestParameters.platformType, requestParameters.persistence, requestParameters.websiteId, requestParameters.deviceDetails, requestParameters.guardData, requestParameters.language, requestParameters.qosLevel, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IAuthenticationServiceApiIAuthenticationServiceBeginAuthSessionViaQRV1PostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iAuthenticationServiceBeginAuthSessionViaQRV1Post(requestParameters: IAuthenticationServiceApiIAuthenticationServiceBeginAuthSessionViaQRV1PostRequest = {}, options?: RawAxiosRequestConfig) {
        return IAuthenticationServiceApiFp(this.configuration).iAuthenticationServiceBeginAuthSessionViaQRV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.deviceFriendlyName, requestParameters.platformType, requestParameters.deviceDetails, requestParameters.websiteId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IAuthenticationServiceApiIAuthenticationServiceGetAuthSessionInfoV1PostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iAuthenticationServiceGetAuthSessionInfoV1Post(requestParameters: IAuthenticationServiceApiIAuthenticationServiceGetAuthSessionInfoV1PostRequest = {}, options?: RawAxiosRequestConfig) {
        return IAuthenticationServiceApiFp(this.configuration).iAuthenticationServiceGetAuthSessionInfoV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.clientId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IAuthenticationServiceApiIAuthenticationServiceGetAuthSessionRiskInfoV1PostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iAuthenticationServiceGetAuthSessionRiskInfoV1Post(requestParameters: IAuthenticationServiceApiIAuthenticationServiceGetAuthSessionRiskInfoV1PostRequest = {}, options?: RawAxiosRequestConfig) {
        return IAuthenticationServiceApiFp(this.configuration).iAuthenticationServiceGetAuthSessionRiskInfoV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.clientId, requestParameters.language, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IAuthenticationServiceApiIAuthenticationServiceGetPasswordRSAPublicKeyV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iAuthenticationServiceGetPasswordRSAPublicKeyV1Get(requestParameters: IAuthenticationServiceApiIAuthenticationServiceGetPasswordRSAPublicKeyV1GetRequest = {}, options?: RawAxiosRequestConfig) {
        return IAuthenticationServiceApiFp(this.configuration).iAuthenticationServiceGetPasswordRSAPublicKeyV1Get(requestParameters.accountName, requestParameters.inputJson, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IAuthenticationServiceApiIAuthenticationServiceNotifyRiskQuizResultsV1PostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iAuthenticationServiceNotifyRiskQuizResultsV1Post(requestParameters: IAuthenticationServiceApiIAuthenticationServiceNotifyRiskQuizResultsV1PostRequest = {}, options?: RawAxiosRequestConfig) {
        return IAuthenticationServiceApiFp(this.configuration).iAuthenticationServiceNotifyRiskQuizResultsV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.clientId, requestParameters.results, requestParameters.selectedAction, requestParameters.didConfirmLogin, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IAuthenticationServiceApiIAuthenticationServicePollAuthSessionStatusV1PostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iAuthenticationServicePollAuthSessionStatusV1Post(requestParameters: IAuthenticationServiceApiIAuthenticationServicePollAuthSessionStatusV1PostRequest = {}, options?: RawAxiosRequestConfig) {
        return IAuthenticationServiceApiFp(this.configuration).iAuthenticationServicePollAuthSessionStatusV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.clientId, requestParameters.requestId, requestParameters.tokenToRevoke, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IAuthenticationServiceApiIAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1PostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1Post(requestParameters: IAuthenticationServiceApiIAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1PostRequest = {}, options?: RawAxiosRequestConfig) {
        return IAuthenticationServiceApiFp(this.configuration).iAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.version, requestParameters.clientId, requestParameters.steamid, requestParameters.signature, requestParameters.confirm, requestParameters.persistence, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IAuthenticationServiceApiIAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1PostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1Post(requestParameters: IAuthenticationServiceApiIAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1PostRequest = {}, options?: RawAxiosRequestConfig) {
        return IAuthenticationServiceApiFp(this.configuration).iAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.clientId, requestParameters.steamid, requestParameters.code, requestParameters.codeType, options).then((request) => request(this.axios, this.basePath));
    }
}

export const IAuthenticationServiceBeginAuthSessionViaCredentialsV1PostFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IAuthenticationServiceBeginAuthSessionViaCredentialsV1PostFormatEnum = typeof IAuthenticationServiceBeginAuthSessionViaCredentialsV1PostFormatEnum[keyof typeof IAuthenticationServiceBeginAuthSessionViaCredentialsV1PostFormatEnum];
export const IAuthenticationServiceBeginAuthSessionViaQRV1PostFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IAuthenticationServiceBeginAuthSessionViaQRV1PostFormatEnum = typeof IAuthenticationServiceBeginAuthSessionViaQRV1PostFormatEnum[keyof typeof IAuthenticationServiceBeginAuthSessionViaQRV1PostFormatEnum];
export const IAuthenticationServiceGetAuthSessionInfoV1PostFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IAuthenticationServiceGetAuthSessionInfoV1PostFormatEnum = typeof IAuthenticationServiceGetAuthSessionInfoV1PostFormatEnum[keyof typeof IAuthenticationServiceGetAuthSessionInfoV1PostFormatEnum];
export const IAuthenticationServiceGetAuthSessionRiskInfoV1PostFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IAuthenticationServiceGetAuthSessionRiskInfoV1PostFormatEnum = typeof IAuthenticationServiceGetAuthSessionRiskInfoV1PostFormatEnum[keyof typeof IAuthenticationServiceGetAuthSessionRiskInfoV1PostFormatEnum];
export const IAuthenticationServiceGetPasswordRSAPublicKeyV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IAuthenticationServiceGetPasswordRSAPublicKeyV1GetFormatEnum = typeof IAuthenticationServiceGetPasswordRSAPublicKeyV1GetFormatEnum[keyof typeof IAuthenticationServiceGetPasswordRSAPublicKeyV1GetFormatEnum];
export const IAuthenticationServiceNotifyRiskQuizResultsV1PostFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IAuthenticationServiceNotifyRiskQuizResultsV1PostFormatEnum = typeof IAuthenticationServiceNotifyRiskQuizResultsV1PostFormatEnum[keyof typeof IAuthenticationServiceNotifyRiskQuizResultsV1PostFormatEnum];
export const IAuthenticationServicePollAuthSessionStatusV1PostFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IAuthenticationServicePollAuthSessionStatusV1PostFormatEnum = typeof IAuthenticationServicePollAuthSessionStatusV1PostFormatEnum[keyof typeof IAuthenticationServicePollAuthSessionStatusV1PostFormatEnum];
export const IAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1PostFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1PostFormatEnum = typeof IAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1PostFormatEnum[keyof typeof IAuthenticationServiceUpdateAuthSessionWithMobileConfirmationV1PostFormatEnum];
export const IAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1PostFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1PostFormatEnum = typeof IAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1PostFormatEnum[keyof typeof IAuthenticationServiceUpdateAuthSessionWithSteamGuardCodeV1PostFormatEnum];
