/* tslint:disable */
/* eslint-disable */
/**
 * Steamworks Web API
 * This is an OpenAPI specification for the Steamworks Web API. For more details on how to use this tool, check out the <a href=\"https://github.com/ceva24/openapi-steamworks-web-api/blob/main/README.md\">README</a>.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * IBroadcastServiceApi - axios parameter creator
 */
export const IBroadcastServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IBroadcastServicePostGameDataFrameRTMPV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [appid] (Required) AppID of the game being broadcasted
         * @param {number} [steamid] (Required) Broadcasters SteamID
         * @param {string} [rtmpToken] (Required) Valid RTMP token for the Broadcaster
         * @param {string} [frameData] (Required) game data frame expressing current state of game (string, zipped, whatever)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iBroadcastServicePostGameDataFrameRTMPV1Post: async (inputJson?: string, format?: IBroadcastServicePostGameDataFrameRTMPV1PostFormatEnum, appid?: number, steamid?: number, rtmpToken?: string, frameData?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IBroadcastService/PostGameDataFrameRTMP/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            if (appid !== undefined) { 
                localVarFormParams.set('appid', appid as any);
            }

            if (steamid !== undefined) { 
                localVarFormParams.set('steamid', steamid as any);
            }

            if (rtmpToken !== undefined) { 
                localVarFormParams.set('rtmp_token', rtmpToken as any);
            }

            if (frameData !== undefined) { 
                localVarFormParams.set('frame_data', frameData as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IBroadcastServiceApi - functional programming interface
 */
export const IBroadcastServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IBroadcastServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IBroadcastServicePostGameDataFrameRTMPV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [appid] (Required) AppID of the game being broadcasted
         * @param {number} [steamid] (Required) Broadcasters SteamID
         * @param {string} [rtmpToken] (Required) Valid RTMP token for the Broadcaster
         * @param {string} [frameData] (Required) game data frame expressing current state of game (string, zipped, whatever)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iBroadcastServicePostGameDataFrameRTMPV1Post(inputJson?: string, format?: IBroadcastServicePostGameDataFrameRTMPV1PostFormatEnum, appid?: number, steamid?: number, rtmpToken?: string, frameData?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iBroadcastServicePostGameDataFrameRTMPV1Post(inputJson, format, appid, steamid, rtmpToken, frameData, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IBroadcastServiceApi.iBroadcastServicePostGameDataFrameRTMPV1Post']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * IBroadcastServiceApi - factory interface
 */
export const IBroadcastServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IBroadcastServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {IBroadcastServiceApiIBroadcastServicePostGameDataFrameRTMPV1PostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iBroadcastServicePostGameDataFrameRTMPV1Post(requestParameters: IBroadcastServiceApiIBroadcastServicePostGameDataFrameRTMPV1PostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iBroadcastServicePostGameDataFrameRTMPV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.appid, requestParameters.steamid, requestParameters.rtmpToken, requestParameters.frameData, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for iBroadcastServicePostGameDataFrameRTMPV1Post operation in IBroadcastServiceApi.
 */
export interface IBroadcastServiceApiIBroadcastServicePostGameDataFrameRTMPV1PostRequest {
    /**
     * An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IBroadcastServicePostGameDataFrameRTMPV1PostFormatEnum

    /**
     * (Required) AppID of the game being broadcasted
     */
    readonly appid?: number

    /**
     * (Required) Broadcasters SteamID
     */
    readonly steamid?: number

    /**
     * (Required) Valid RTMP token for the Broadcaster
     */
    readonly rtmpToken?: string

    /**
     * (Required) game data frame expressing current state of game (string, zipped, whatever)
     */
    readonly frameData?: string
}

/**
 * IBroadcastServiceApi - object-oriented interface
 */
export class IBroadcastServiceApi extends BaseAPI {
    /**
     * 
     * @param {IBroadcastServiceApiIBroadcastServicePostGameDataFrameRTMPV1PostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iBroadcastServicePostGameDataFrameRTMPV1Post(requestParameters: IBroadcastServiceApiIBroadcastServicePostGameDataFrameRTMPV1PostRequest = {}, options?: RawAxiosRequestConfig) {
        return IBroadcastServiceApiFp(this.configuration).iBroadcastServicePostGameDataFrameRTMPV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.appid, requestParameters.steamid, requestParameters.rtmpToken, requestParameters.frameData, options).then((request) => request(this.axios, this.basePath));
    }
}

export const IBroadcastServicePostGameDataFrameRTMPV1PostFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IBroadcastServicePostGameDataFrameRTMPV1PostFormatEnum = typeof IBroadcastServicePostGameDataFrameRTMPV1PostFormatEnum[keyof typeof IBroadcastServicePostGameDataFrameRTMPV1PostFormatEnum];
