/* tslint:disable */
/* eslint-disable */
/**
 * Steamworks Web API
 * This is an OpenAPI specification for the Steamworks Web API. For more details on how to use this tool, check out the <a href=\"https://github.com/ceva24/openapi-steamworks-web-api/blob/main/README.md\">README</a>.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * ICSGOTournamentsApi - axios parameter creator
 */
export const ICSGOTournamentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} event The event ID
         * @param {number} steamid The SteamID of the user inventory
         * @param {string} steamidkey Authentication obtained from the SteamID
         * @param {ICSGOTournaments730GetTournamentFantasyLineupV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iCSGOTournaments730GetTournamentFantasyLineupV1Get: async (event: number, steamid: number, steamidkey: string, format?: ICSGOTournaments730GetTournamentFantasyLineupV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'event' is not null or undefined
            assertParamExists('iCSGOTournaments730GetTournamentFantasyLineupV1Get', 'event', event)
            // verify required parameter 'steamid' is not null or undefined
            assertParamExists('iCSGOTournaments730GetTournamentFantasyLineupV1Get', 'steamid', steamid)
            // verify required parameter 'steamidkey' is not null or undefined
            assertParamExists('iCSGOTournaments730GetTournamentFantasyLineupV1Get', 'steamidkey', steamidkey)
            const localVarPath = `/ICSGOTournaments_730/GetTournamentFantasyLineup/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (event !== undefined) {
                localVarQueryParameter['event'] = event;
            }

            if (steamid !== undefined) {
                localVarQueryParameter['steamid'] = steamid;
            }

            if (steamidkey !== undefined) {
                localVarQueryParameter['steamidkey'] = steamidkey;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} event The event ID
         * @param {number} steamid The SteamID of the user inventory
         * @param {string} steamidkey Authentication obtained from the SteamID
         * @param {ICSGOTournaments730GetTournamentItemsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iCSGOTournaments730GetTournamentItemsV1Get: async (event: number, steamid: number, steamidkey: string, format?: ICSGOTournaments730GetTournamentItemsV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'event' is not null or undefined
            assertParamExists('iCSGOTournaments730GetTournamentItemsV1Get', 'event', event)
            // verify required parameter 'steamid' is not null or undefined
            assertParamExists('iCSGOTournaments730GetTournamentItemsV1Get', 'steamid', steamid)
            // verify required parameter 'steamidkey' is not null or undefined
            assertParamExists('iCSGOTournaments730GetTournamentItemsV1Get', 'steamidkey', steamidkey)
            const localVarPath = `/ICSGOTournaments_730/GetTournamentItems/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (event !== undefined) {
                localVarQueryParameter['event'] = event;
            }

            if (steamid !== undefined) {
                localVarQueryParameter['steamid'] = steamid;
            }

            if (steamidkey !== undefined) {
                localVarQueryParameter['steamidkey'] = steamidkey;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} event The event ID
         * @param {ICSGOTournaments730GetTournamentLayoutV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iCSGOTournaments730GetTournamentLayoutV1Get: async (event: number, format?: ICSGOTournaments730GetTournamentLayoutV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'event' is not null or undefined
            assertParamExists('iCSGOTournaments730GetTournamentLayoutV1Get', 'event', event)
            const localVarPath = `/ICSGOTournaments_730/GetTournamentLayout/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (event !== undefined) {
                localVarQueryParameter['event'] = event;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} event The event ID
         * @param {number} steamid The SteamID of the user inventory
         * @param {string} steamidkey Authentication obtained from the SteamID
         * @param {ICSGOTournaments730GetTournamentPredictionsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iCSGOTournaments730GetTournamentPredictionsV1Get: async (event: number, steamid: number, steamidkey: string, format?: ICSGOTournaments730GetTournamentPredictionsV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'event' is not null or undefined
            assertParamExists('iCSGOTournaments730GetTournamentPredictionsV1Get', 'event', event)
            // verify required parameter 'steamid' is not null or undefined
            assertParamExists('iCSGOTournaments730GetTournamentPredictionsV1Get', 'steamid', steamid)
            // verify required parameter 'steamidkey' is not null or undefined
            assertParamExists('iCSGOTournaments730GetTournamentPredictionsV1Get', 'steamidkey', steamidkey)
            const localVarPath = `/ICSGOTournaments_730/GetTournamentPredictions/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (event !== undefined) {
                localVarQueryParameter['event'] = event;
            }

            if (steamid !== undefined) {
                localVarQueryParameter['steamid'] = steamid;
            }

            if (steamidkey !== undefined) {
                localVarQueryParameter['steamidkey'] = steamidkey;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} event The event ID
         * @param {number} steamid The SteamID of the user inventory
         * @param {string} steamidkey Authentication obtained from the SteamID
         * @param {number} sectionid Event section id
         * @param {number} pickid0 PickID to select for the slot
         * @param {number} itemid0 ItemID to lock in for the pick
         * @param {number} pickid1 PickID to select for the slot
         * @param {number} itemid1 ItemID to lock in for the pick
         * @param {number} pickid2 PickID to select for the slot
         * @param {number} itemid2 ItemID to lock in for the pick
         * @param {number} pickid3 PickID to select for the slot
         * @param {number} itemid3 ItemID to lock in for the pick
         * @param {number} pickid4 PickID to select for the slot
         * @param {number} itemid4 ItemID to lock in for the pick
         * @param {ICSGOTournaments730UploadTournamentFantasyLineupV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iCSGOTournaments730UploadTournamentFantasyLineupV1Post: async (event: number, steamid: number, steamidkey: string, sectionid: number, pickid0: number, itemid0: number, pickid1: number, itemid1: number, pickid2: number, itemid2: number, pickid3: number, itemid3: number, pickid4: number, itemid4: number, format?: ICSGOTournaments730UploadTournamentFantasyLineupV1PostFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'event' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentFantasyLineupV1Post', 'event', event)
            // verify required parameter 'steamid' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentFantasyLineupV1Post', 'steamid', steamid)
            // verify required parameter 'steamidkey' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentFantasyLineupV1Post', 'steamidkey', steamidkey)
            // verify required parameter 'sectionid' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentFantasyLineupV1Post', 'sectionid', sectionid)
            // verify required parameter 'pickid0' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentFantasyLineupV1Post', 'pickid0', pickid0)
            // verify required parameter 'itemid0' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentFantasyLineupV1Post', 'itemid0', itemid0)
            // verify required parameter 'pickid1' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentFantasyLineupV1Post', 'pickid1', pickid1)
            // verify required parameter 'itemid1' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentFantasyLineupV1Post', 'itemid1', itemid1)
            // verify required parameter 'pickid2' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentFantasyLineupV1Post', 'pickid2', pickid2)
            // verify required parameter 'itemid2' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentFantasyLineupV1Post', 'itemid2', itemid2)
            // verify required parameter 'pickid3' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentFantasyLineupV1Post', 'pickid3', pickid3)
            // verify required parameter 'itemid3' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentFantasyLineupV1Post', 'itemid3', itemid3)
            // verify required parameter 'pickid4' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentFantasyLineupV1Post', 'pickid4', pickid4)
            // verify required parameter 'itemid4' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentFantasyLineupV1Post', 'itemid4', itemid4)
            const localVarPath = `/ICSGOTournaments_730/UploadTournamentFantasyLineup/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            if (event !== undefined) { 
                localVarFormParams.set('event', event as any);
            }

            if (steamid !== undefined) { 
                localVarFormParams.set('steamid', steamid as any);
            }

            if (steamidkey !== undefined) { 
                localVarFormParams.set('steamidkey', steamidkey as any);
            }

            if (sectionid !== undefined) { 
                localVarFormParams.set('sectionid', sectionid as any);
            }

            if (pickid0 !== undefined) { 
                localVarFormParams.set('pickid0', pickid0 as any);
            }

            if (itemid0 !== undefined) { 
                localVarFormParams.set('itemid0', itemid0 as any);
            }

            if (pickid1 !== undefined) { 
                localVarFormParams.set('pickid1', pickid1 as any);
            }

            if (itemid1 !== undefined) { 
                localVarFormParams.set('itemid1', itemid1 as any);
            }

            if (pickid2 !== undefined) { 
                localVarFormParams.set('pickid2', pickid2 as any);
            }

            if (itemid2 !== undefined) { 
                localVarFormParams.set('itemid2', itemid2 as any);
            }

            if (pickid3 !== undefined) { 
                localVarFormParams.set('pickid3', pickid3 as any);
            }

            if (itemid3 !== undefined) { 
                localVarFormParams.set('itemid3', itemid3 as any);
            }

            if (pickid4 !== undefined) { 
                localVarFormParams.set('pickid4', pickid4 as any);
            }

            if (itemid4 !== undefined) { 
                localVarFormParams.set('itemid4', itemid4 as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} event The event ID
         * @param {number} steamid The SteamID of the user inventory
         * @param {string} steamidkey Authentication obtained from the SteamID
         * @param {number} sectionid Event section id
         * @param {number} groupid Event group id
         * @param {number} index Index in group
         * @param {number} pickid Pick ID to select
         * @param {number} itemid ItemID to lock in for the pick
         * @param {ICSGOTournaments730UploadTournamentPredictionsV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iCSGOTournaments730UploadTournamentPredictionsV1Post: async (event: number, steamid: number, steamidkey: string, sectionid: number, groupid: number, index: number, pickid: number, itemid: number, format?: ICSGOTournaments730UploadTournamentPredictionsV1PostFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'event' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentPredictionsV1Post', 'event', event)
            // verify required parameter 'steamid' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentPredictionsV1Post', 'steamid', steamid)
            // verify required parameter 'steamidkey' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentPredictionsV1Post', 'steamidkey', steamidkey)
            // verify required parameter 'sectionid' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentPredictionsV1Post', 'sectionid', sectionid)
            // verify required parameter 'groupid' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentPredictionsV1Post', 'groupid', groupid)
            // verify required parameter 'index' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentPredictionsV1Post', 'index', index)
            // verify required parameter 'pickid' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentPredictionsV1Post', 'pickid', pickid)
            // verify required parameter 'itemid' is not null or undefined
            assertParamExists('iCSGOTournaments730UploadTournamentPredictionsV1Post', 'itemid', itemid)
            const localVarPath = `/ICSGOTournaments_730/UploadTournamentPredictions/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            if (event !== undefined) { 
                localVarFormParams.set('event', event as any);
            }

            if (steamid !== undefined) { 
                localVarFormParams.set('steamid', steamid as any);
            }

            if (steamidkey !== undefined) { 
                localVarFormParams.set('steamidkey', steamidkey as any);
            }

            if (sectionid !== undefined) { 
                localVarFormParams.set('sectionid', sectionid as any);
            }

            if (groupid !== undefined) { 
                localVarFormParams.set('groupid', groupid as any);
            }

            if (index !== undefined) { 
                localVarFormParams.set('index', index as any);
            }

            if (pickid !== undefined) { 
                localVarFormParams.set('pickid', pickid as any);
            }

            if (itemid !== undefined) { 
                localVarFormParams.set('itemid', itemid as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ICSGOTournamentsApi - functional programming interface
 */
export const ICSGOTournamentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ICSGOTournamentsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} event The event ID
         * @param {number} steamid The SteamID of the user inventory
         * @param {string} steamidkey Authentication obtained from the SteamID
         * @param {ICSGOTournaments730GetTournamentFantasyLineupV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iCSGOTournaments730GetTournamentFantasyLineupV1Get(event: number, steamid: number, steamidkey: string, format?: ICSGOTournaments730GetTournamentFantasyLineupV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iCSGOTournaments730GetTournamentFantasyLineupV1Get(event, steamid, steamidkey, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ICSGOTournamentsApi.iCSGOTournaments730GetTournamentFantasyLineupV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} event The event ID
         * @param {number} steamid The SteamID of the user inventory
         * @param {string} steamidkey Authentication obtained from the SteamID
         * @param {ICSGOTournaments730GetTournamentItemsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iCSGOTournaments730GetTournamentItemsV1Get(event: number, steamid: number, steamidkey: string, format?: ICSGOTournaments730GetTournamentItemsV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iCSGOTournaments730GetTournamentItemsV1Get(event, steamid, steamidkey, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ICSGOTournamentsApi.iCSGOTournaments730GetTournamentItemsV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} event The event ID
         * @param {ICSGOTournaments730GetTournamentLayoutV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iCSGOTournaments730GetTournamentLayoutV1Get(event: number, format?: ICSGOTournaments730GetTournamentLayoutV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iCSGOTournaments730GetTournamentLayoutV1Get(event, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ICSGOTournamentsApi.iCSGOTournaments730GetTournamentLayoutV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} event The event ID
         * @param {number} steamid The SteamID of the user inventory
         * @param {string} steamidkey Authentication obtained from the SteamID
         * @param {ICSGOTournaments730GetTournamentPredictionsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iCSGOTournaments730GetTournamentPredictionsV1Get(event: number, steamid: number, steamidkey: string, format?: ICSGOTournaments730GetTournamentPredictionsV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iCSGOTournaments730GetTournamentPredictionsV1Get(event, steamid, steamidkey, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ICSGOTournamentsApi.iCSGOTournaments730GetTournamentPredictionsV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} event The event ID
         * @param {number} steamid The SteamID of the user inventory
         * @param {string} steamidkey Authentication obtained from the SteamID
         * @param {number} sectionid Event section id
         * @param {number} pickid0 PickID to select for the slot
         * @param {number} itemid0 ItemID to lock in for the pick
         * @param {number} pickid1 PickID to select for the slot
         * @param {number} itemid1 ItemID to lock in for the pick
         * @param {number} pickid2 PickID to select for the slot
         * @param {number} itemid2 ItemID to lock in for the pick
         * @param {number} pickid3 PickID to select for the slot
         * @param {number} itemid3 ItemID to lock in for the pick
         * @param {number} pickid4 PickID to select for the slot
         * @param {number} itemid4 ItemID to lock in for the pick
         * @param {ICSGOTournaments730UploadTournamentFantasyLineupV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iCSGOTournaments730UploadTournamentFantasyLineupV1Post(event: number, steamid: number, steamidkey: string, sectionid: number, pickid0: number, itemid0: number, pickid1: number, itemid1: number, pickid2: number, itemid2: number, pickid3: number, itemid3: number, pickid4: number, itemid4: number, format?: ICSGOTournaments730UploadTournamentFantasyLineupV1PostFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iCSGOTournaments730UploadTournamentFantasyLineupV1Post(event, steamid, steamidkey, sectionid, pickid0, itemid0, pickid1, itemid1, pickid2, itemid2, pickid3, itemid3, pickid4, itemid4, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ICSGOTournamentsApi.iCSGOTournaments730UploadTournamentFantasyLineupV1Post']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} event The event ID
         * @param {number} steamid The SteamID of the user inventory
         * @param {string} steamidkey Authentication obtained from the SteamID
         * @param {number} sectionid Event section id
         * @param {number} groupid Event group id
         * @param {number} index Index in group
         * @param {number} pickid Pick ID to select
         * @param {number} itemid ItemID to lock in for the pick
         * @param {ICSGOTournaments730UploadTournamentPredictionsV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iCSGOTournaments730UploadTournamentPredictionsV1Post(event: number, steamid: number, steamidkey: string, sectionid: number, groupid: number, index: number, pickid: number, itemid: number, format?: ICSGOTournaments730UploadTournamentPredictionsV1PostFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iCSGOTournaments730UploadTournamentPredictionsV1Post(event, steamid, steamidkey, sectionid, groupid, index, pickid, itemid, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ICSGOTournamentsApi.iCSGOTournaments730UploadTournamentPredictionsV1Post']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ICSGOTournamentsApi - factory interface
 */
export const ICSGOTournamentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ICSGOTournamentsApiFp(configuration)
    return {
        /**
         * 
         * @param {ICSGOTournamentsApiICSGOTournaments730GetTournamentFantasyLineupV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iCSGOTournaments730GetTournamentFantasyLineupV1Get(requestParameters: ICSGOTournamentsApiICSGOTournaments730GetTournamentFantasyLineupV1GetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iCSGOTournaments730GetTournamentFantasyLineupV1Get(requestParameters.event, requestParameters.steamid, requestParameters.steamidkey, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ICSGOTournamentsApiICSGOTournaments730GetTournamentItemsV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iCSGOTournaments730GetTournamentItemsV1Get(requestParameters: ICSGOTournamentsApiICSGOTournaments730GetTournamentItemsV1GetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iCSGOTournaments730GetTournamentItemsV1Get(requestParameters.event, requestParameters.steamid, requestParameters.steamidkey, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ICSGOTournamentsApiICSGOTournaments730GetTournamentLayoutV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iCSGOTournaments730GetTournamentLayoutV1Get(requestParameters: ICSGOTournamentsApiICSGOTournaments730GetTournamentLayoutV1GetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iCSGOTournaments730GetTournamentLayoutV1Get(requestParameters.event, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ICSGOTournamentsApiICSGOTournaments730GetTournamentPredictionsV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iCSGOTournaments730GetTournamentPredictionsV1Get(requestParameters: ICSGOTournamentsApiICSGOTournaments730GetTournamentPredictionsV1GetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iCSGOTournaments730GetTournamentPredictionsV1Get(requestParameters.event, requestParameters.steamid, requestParameters.steamidkey, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ICSGOTournamentsApiICSGOTournaments730UploadTournamentFantasyLineupV1PostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iCSGOTournaments730UploadTournamentFantasyLineupV1Post(requestParameters: ICSGOTournamentsApiICSGOTournaments730UploadTournamentFantasyLineupV1PostRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iCSGOTournaments730UploadTournamentFantasyLineupV1Post(requestParameters.event, requestParameters.steamid, requestParameters.steamidkey, requestParameters.sectionid, requestParameters.pickid0, requestParameters.itemid0, requestParameters.pickid1, requestParameters.itemid1, requestParameters.pickid2, requestParameters.itemid2, requestParameters.pickid3, requestParameters.itemid3, requestParameters.pickid4, requestParameters.itemid4, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ICSGOTournamentsApiICSGOTournaments730UploadTournamentPredictionsV1PostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iCSGOTournaments730UploadTournamentPredictionsV1Post(requestParameters: ICSGOTournamentsApiICSGOTournaments730UploadTournamentPredictionsV1PostRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iCSGOTournaments730UploadTournamentPredictionsV1Post(requestParameters.event, requestParameters.steamid, requestParameters.steamidkey, requestParameters.sectionid, requestParameters.groupid, requestParameters.index, requestParameters.pickid, requestParameters.itemid, requestParameters.format, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for iCSGOTournaments730GetTournamentFantasyLineupV1Get operation in ICSGOTournamentsApi.
 */
export interface ICSGOTournamentsApiICSGOTournaments730GetTournamentFantasyLineupV1GetRequest {
    /**
     * The event ID
     */
    readonly event: number

    /**
     * The SteamID of the user inventory
     */
    readonly steamid: number

    /**
     * Authentication obtained from the SteamID
     */
    readonly steamidkey: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: ICSGOTournaments730GetTournamentFantasyLineupV1GetFormatEnum
}

/**
 * Request parameters for iCSGOTournaments730GetTournamentItemsV1Get operation in ICSGOTournamentsApi.
 */
export interface ICSGOTournamentsApiICSGOTournaments730GetTournamentItemsV1GetRequest {
    /**
     * The event ID
     */
    readonly event: number

    /**
     * The SteamID of the user inventory
     */
    readonly steamid: number

    /**
     * Authentication obtained from the SteamID
     */
    readonly steamidkey: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: ICSGOTournaments730GetTournamentItemsV1GetFormatEnum
}

/**
 * Request parameters for iCSGOTournaments730GetTournamentLayoutV1Get operation in ICSGOTournamentsApi.
 */
export interface ICSGOTournamentsApiICSGOTournaments730GetTournamentLayoutV1GetRequest {
    /**
     * The event ID
     */
    readonly event: number

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: ICSGOTournaments730GetTournamentLayoutV1GetFormatEnum
}

/**
 * Request parameters for iCSGOTournaments730GetTournamentPredictionsV1Get operation in ICSGOTournamentsApi.
 */
export interface ICSGOTournamentsApiICSGOTournaments730GetTournamentPredictionsV1GetRequest {
    /**
     * The event ID
     */
    readonly event: number

    /**
     * The SteamID of the user inventory
     */
    readonly steamid: number

    /**
     * Authentication obtained from the SteamID
     */
    readonly steamidkey: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: ICSGOTournaments730GetTournamentPredictionsV1GetFormatEnum
}

/**
 * Request parameters for iCSGOTournaments730UploadTournamentFantasyLineupV1Post operation in ICSGOTournamentsApi.
 */
export interface ICSGOTournamentsApiICSGOTournaments730UploadTournamentFantasyLineupV1PostRequest {
    /**
     * The event ID
     */
    readonly event: number

    /**
     * The SteamID of the user inventory
     */
    readonly steamid: number

    /**
     * Authentication obtained from the SteamID
     */
    readonly steamidkey: string

    /**
     * Event section id
     */
    readonly sectionid: number

    /**
     * PickID to select for the slot
     */
    readonly pickid0: number

    /**
     * ItemID to lock in for the pick
     */
    readonly itemid0: number

    /**
     * PickID to select for the slot
     */
    readonly pickid1: number

    /**
     * ItemID to lock in for the pick
     */
    readonly itemid1: number

    /**
     * PickID to select for the slot
     */
    readonly pickid2: number

    /**
     * ItemID to lock in for the pick
     */
    readonly itemid2: number

    /**
     * PickID to select for the slot
     */
    readonly pickid3: number

    /**
     * ItemID to lock in for the pick
     */
    readonly itemid3: number

    /**
     * PickID to select for the slot
     */
    readonly pickid4: number

    /**
     * ItemID to lock in for the pick
     */
    readonly itemid4: number

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: ICSGOTournaments730UploadTournamentFantasyLineupV1PostFormatEnum
}

/**
 * Request parameters for iCSGOTournaments730UploadTournamentPredictionsV1Post operation in ICSGOTournamentsApi.
 */
export interface ICSGOTournamentsApiICSGOTournaments730UploadTournamentPredictionsV1PostRequest {
    /**
     * The event ID
     */
    readonly event: number

    /**
     * The SteamID of the user inventory
     */
    readonly steamid: number

    /**
     * Authentication obtained from the SteamID
     */
    readonly steamidkey: string

    /**
     * Event section id
     */
    readonly sectionid: number

    /**
     * Event group id
     */
    readonly groupid: number

    /**
     * Index in group
     */
    readonly index: number

    /**
     * Pick ID to select
     */
    readonly pickid: number

    /**
     * ItemID to lock in for the pick
     */
    readonly itemid: number

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: ICSGOTournaments730UploadTournamentPredictionsV1PostFormatEnum
}

/**
 * ICSGOTournamentsApi - object-oriented interface
 */
export class ICSGOTournamentsApi extends BaseAPI {
    /**
     * 
     * @param {ICSGOTournamentsApiICSGOTournaments730GetTournamentFantasyLineupV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iCSGOTournaments730GetTournamentFantasyLineupV1Get(requestParameters: ICSGOTournamentsApiICSGOTournaments730GetTournamentFantasyLineupV1GetRequest, options?: RawAxiosRequestConfig) {
        return ICSGOTournamentsApiFp(this.configuration).iCSGOTournaments730GetTournamentFantasyLineupV1Get(requestParameters.event, requestParameters.steamid, requestParameters.steamidkey, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ICSGOTournamentsApiICSGOTournaments730GetTournamentItemsV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iCSGOTournaments730GetTournamentItemsV1Get(requestParameters: ICSGOTournamentsApiICSGOTournaments730GetTournamentItemsV1GetRequest, options?: RawAxiosRequestConfig) {
        return ICSGOTournamentsApiFp(this.configuration).iCSGOTournaments730GetTournamentItemsV1Get(requestParameters.event, requestParameters.steamid, requestParameters.steamidkey, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ICSGOTournamentsApiICSGOTournaments730GetTournamentLayoutV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iCSGOTournaments730GetTournamentLayoutV1Get(requestParameters: ICSGOTournamentsApiICSGOTournaments730GetTournamentLayoutV1GetRequest, options?: RawAxiosRequestConfig) {
        return ICSGOTournamentsApiFp(this.configuration).iCSGOTournaments730GetTournamentLayoutV1Get(requestParameters.event, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ICSGOTournamentsApiICSGOTournaments730GetTournamentPredictionsV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iCSGOTournaments730GetTournamentPredictionsV1Get(requestParameters: ICSGOTournamentsApiICSGOTournaments730GetTournamentPredictionsV1GetRequest, options?: RawAxiosRequestConfig) {
        return ICSGOTournamentsApiFp(this.configuration).iCSGOTournaments730GetTournamentPredictionsV1Get(requestParameters.event, requestParameters.steamid, requestParameters.steamidkey, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ICSGOTournamentsApiICSGOTournaments730UploadTournamentFantasyLineupV1PostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iCSGOTournaments730UploadTournamentFantasyLineupV1Post(requestParameters: ICSGOTournamentsApiICSGOTournaments730UploadTournamentFantasyLineupV1PostRequest, options?: RawAxiosRequestConfig) {
        return ICSGOTournamentsApiFp(this.configuration).iCSGOTournaments730UploadTournamentFantasyLineupV1Post(requestParameters.event, requestParameters.steamid, requestParameters.steamidkey, requestParameters.sectionid, requestParameters.pickid0, requestParameters.itemid0, requestParameters.pickid1, requestParameters.itemid1, requestParameters.pickid2, requestParameters.itemid2, requestParameters.pickid3, requestParameters.itemid3, requestParameters.pickid4, requestParameters.itemid4, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ICSGOTournamentsApiICSGOTournaments730UploadTournamentPredictionsV1PostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iCSGOTournaments730UploadTournamentPredictionsV1Post(requestParameters: ICSGOTournamentsApiICSGOTournaments730UploadTournamentPredictionsV1PostRequest, options?: RawAxiosRequestConfig) {
        return ICSGOTournamentsApiFp(this.configuration).iCSGOTournaments730UploadTournamentPredictionsV1Post(requestParameters.event, requestParameters.steamid, requestParameters.steamidkey, requestParameters.sectionid, requestParameters.groupid, requestParameters.index, requestParameters.pickid, requestParameters.itemid, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }
}

export const ICSGOTournaments730GetTournamentFantasyLineupV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type ICSGOTournaments730GetTournamentFantasyLineupV1GetFormatEnum = typeof ICSGOTournaments730GetTournamentFantasyLineupV1GetFormatEnum[keyof typeof ICSGOTournaments730GetTournamentFantasyLineupV1GetFormatEnum];
export const ICSGOTournaments730GetTournamentItemsV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type ICSGOTournaments730GetTournamentItemsV1GetFormatEnum = typeof ICSGOTournaments730GetTournamentItemsV1GetFormatEnum[keyof typeof ICSGOTournaments730GetTournamentItemsV1GetFormatEnum];
export const ICSGOTournaments730GetTournamentLayoutV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type ICSGOTournaments730GetTournamentLayoutV1GetFormatEnum = typeof ICSGOTournaments730GetTournamentLayoutV1GetFormatEnum[keyof typeof ICSGOTournaments730GetTournamentLayoutV1GetFormatEnum];
export const ICSGOTournaments730GetTournamentPredictionsV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type ICSGOTournaments730GetTournamentPredictionsV1GetFormatEnum = typeof ICSGOTournaments730GetTournamentPredictionsV1GetFormatEnum[keyof typeof ICSGOTournaments730GetTournamentPredictionsV1GetFormatEnum];
export const ICSGOTournaments730UploadTournamentFantasyLineupV1PostFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type ICSGOTournaments730UploadTournamentFantasyLineupV1PostFormatEnum = typeof ICSGOTournaments730UploadTournamentFantasyLineupV1PostFormatEnum[keyof typeof ICSGOTournaments730UploadTournamentFantasyLineupV1PostFormatEnum];
export const ICSGOTournaments730UploadTournamentPredictionsV1PostFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type ICSGOTournaments730UploadTournamentPredictionsV1PostFormatEnum = typeof ICSGOTournaments730UploadTournamentPredictionsV1PostFormatEnum[keyof typeof ICSGOTournaments730UploadTournamentPredictionsV1PostFormatEnum];
