/* tslint:disable */
/* eslint-disable */
/**
 * Steamworks Web API
 * This is an OpenAPI specification for the Steamworks Web API. For more details on how to use this tool, check out the <a href=\"https://github.com/ceva24/openapi-steamworks-web-api/blob/main/README.md\">README</a>.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * ICSGOServersApi - axios parameter creator
 */
export const ICSGOServersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} interval What recent interval is requested, possible values: day, week, month
         * @param {string} gamemode What game mode is requested, possible values: competitive, casual
         * @param {string} mapgroup What maps are requested, possible values: operation
         * @param {ICSGOServers730GetGameMapsPlaytimeV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iCSGOServers730GetGameMapsPlaytimeV1Get: async (interval: string, gamemode: string, mapgroup: string, format?: ICSGOServers730GetGameMapsPlaytimeV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'interval' is not null or undefined
            assertParamExists('iCSGOServers730GetGameMapsPlaytimeV1Get', 'interval', interval)
            // verify required parameter 'gamemode' is not null or undefined
            assertParamExists('iCSGOServers730GetGameMapsPlaytimeV1Get', 'gamemode', gamemode)
            // verify required parameter 'mapgroup' is not null or undefined
            assertParamExists('iCSGOServers730GetGameMapsPlaytimeV1Get', 'mapgroup', mapgroup)
            const localVarPath = `/ICSGOServers_730/GetGameMapsPlaytime/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (interval !== undefined) {
                localVarQueryParameter['interval'] = interval;
            }

            if (gamemode !== undefined) {
                localVarQueryParameter['gamemode'] = gamemode;
            }

            if (mapgroup !== undefined) {
                localVarQueryParameter['mapgroup'] = mapgroup;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ICSGOServers730GetGameServersStatusV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iCSGOServers730GetGameServersStatusV1Get: async (format?: ICSGOServers730GetGameServersStatusV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ICSGOServers_730/GetGameServersStatus/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ICSGOServersApi - functional programming interface
 */
export const ICSGOServersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ICSGOServersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} interval What recent interval is requested, possible values: day, week, month
         * @param {string} gamemode What game mode is requested, possible values: competitive, casual
         * @param {string} mapgroup What maps are requested, possible values: operation
         * @param {ICSGOServers730GetGameMapsPlaytimeV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iCSGOServers730GetGameMapsPlaytimeV1Get(interval: string, gamemode: string, mapgroup: string, format?: ICSGOServers730GetGameMapsPlaytimeV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iCSGOServers730GetGameMapsPlaytimeV1Get(interval, gamemode, mapgroup, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ICSGOServersApi.iCSGOServers730GetGameMapsPlaytimeV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ICSGOServers730GetGameServersStatusV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iCSGOServers730GetGameServersStatusV1Get(format?: ICSGOServers730GetGameServersStatusV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iCSGOServers730GetGameServersStatusV1Get(format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ICSGOServersApi.iCSGOServers730GetGameServersStatusV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ICSGOServersApi - factory interface
 */
export const ICSGOServersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ICSGOServersApiFp(configuration)
    return {
        /**
         * 
         * @param {ICSGOServersApiICSGOServers730GetGameMapsPlaytimeV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iCSGOServers730GetGameMapsPlaytimeV1Get(requestParameters: ICSGOServersApiICSGOServers730GetGameMapsPlaytimeV1GetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iCSGOServers730GetGameMapsPlaytimeV1Get(requestParameters.interval, requestParameters.gamemode, requestParameters.mapgroup, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ICSGOServersApiICSGOServers730GetGameServersStatusV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iCSGOServers730GetGameServersStatusV1Get(requestParameters: ICSGOServersApiICSGOServers730GetGameServersStatusV1GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iCSGOServers730GetGameServersStatusV1Get(requestParameters.format, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for iCSGOServers730GetGameMapsPlaytimeV1Get operation in ICSGOServersApi.
 */
export interface ICSGOServersApiICSGOServers730GetGameMapsPlaytimeV1GetRequest {
    /**
     * What recent interval is requested, possible values: day, week, month
     */
    readonly interval: string

    /**
     * What game mode is requested, possible values: competitive, casual
     */
    readonly gamemode: string

    /**
     * What maps are requested, possible values: operation
     */
    readonly mapgroup: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: ICSGOServers730GetGameMapsPlaytimeV1GetFormatEnum
}

/**
 * Request parameters for iCSGOServers730GetGameServersStatusV1Get operation in ICSGOServersApi.
 */
export interface ICSGOServersApiICSGOServers730GetGameServersStatusV1GetRequest {
    /**
     * The format of the response. Defaults to json
     */
    readonly format?: ICSGOServers730GetGameServersStatusV1GetFormatEnum
}

/**
 * ICSGOServersApi - object-oriented interface
 */
export class ICSGOServersApi extends BaseAPI {
    /**
     * 
     * @param {ICSGOServersApiICSGOServers730GetGameMapsPlaytimeV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iCSGOServers730GetGameMapsPlaytimeV1Get(requestParameters: ICSGOServersApiICSGOServers730GetGameMapsPlaytimeV1GetRequest, options?: RawAxiosRequestConfig) {
        return ICSGOServersApiFp(this.configuration).iCSGOServers730GetGameMapsPlaytimeV1Get(requestParameters.interval, requestParameters.gamemode, requestParameters.mapgroup, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ICSGOServersApiICSGOServers730GetGameServersStatusV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iCSGOServers730GetGameServersStatusV1Get(requestParameters: ICSGOServersApiICSGOServers730GetGameServersStatusV1GetRequest = {}, options?: RawAxiosRequestConfig) {
        return ICSGOServersApiFp(this.configuration).iCSGOServers730GetGameServersStatusV1Get(requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }
}

export const ICSGOServers730GetGameMapsPlaytimeV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type ICSGOServers730GetGameMapsPlaytimeV1GetFormatEnum = typeof ICSGOServers730GetGameMapsPlaytimeV1GetFormatEnum[keyof typeof ICSGOServers730GetGameMapsPlaytimeV1GetFormatEnum];
export const ICSGOServers730GetGameServersStatusV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type ICSGOServers730GetGameServersStatusV1GetFormatEnum = typeof ICSGOServers730GetGameServersStatusV1GetFormatEnum[keyof typeof ICSGOServers730GetGameServersStatusV1GetFormatEnum];
