/* tslint:disable */
/* eslint-disable */
/**
 * Steamworks Web API
 * This is an OpenAPI specification for the Steamworks Web API. For more details on how to use this tool, check out the <a href=\"https://github.com/ceva24/openapi-steamworks-web-api/blob/main/README.md\">README</a>.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * IDOTA2StreamSystemApi - axios parameter creator
 */
export const IDOTA2StreamSystemApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} broadcasterSteamId 64-bit Steam ID of the broadcaster
         * @param {number} [leagueId] LeagueID to use if we aren\&#39;t in a lobby
         * @param {IDOTA2StreamSystem570GetBroadcasterInfoV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iDOTA2StreamSystem570GetBroadcasterInfoV1Get: async (broadcasterSteamId: number, leagueId?: number, format?: IDOTA2StreamSystem570GetBroadcasterInfoV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'broadcasterSteamId' is not null or undefined
            assertParamExists('iDOTA2StreamSystem570GetBroadcasterInfoV1Get', 'broadcasterSteamId', broadcasterSteamId)
            const localVarPath = `/IDOTA2StreamSystem_570/GetBroadcasterInfo/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (broadcasterSteamId !== undefined) {
                localVarQueryParameter['broadcaster_steam_id'] = broadcasterSteamId;
            }

            if (leagueId !== undefined) {
                localVarQueryParameter['league_id'] = leagueId;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IDOTA2StreamSystemApi - functional programming interface
 */
export const IDOTA2StreamSystemApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IDOTA2StreamSystemApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} broadcasterSteamId 64-bit Steam ID of the broadcaster
         * @param {number} [leagueId] LeagueID to use if we aren\&#39;t in a lobby
         * @param {IDOTA2StreamSystem570GetBroadcasterInfoV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iDOTA2StreamSystem570GetBroadcasterInfoV1Get(broadcasterSteamId: number, leagueId?: number, format?: IDOTA2StreamSystem570GetBroadcasterInfoV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iDOTA2StreamSystem570GetBroadcasterInfoV1Get(broadcasterSteamId, leagueId, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IDOTA2StreamSystemApi.iDOTA2StreamSystem570GetBroadcasterInfoV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * IDOTA2StreamSystemApi - factory interface
 */
export const IDOTA2StreamSystemApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IDOTA2StreamSystemApiFp(configuration)
    return {
        /**
         * 
         * @param {IDOTA2StreamSystemApiIDOTA2StreamSystem570GetBroadcasterInfoV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iDOTA2StreamSystem570GetBroadcasterInfoV1Get(requestParameters: IDOTA2StreamSystemApiIDOTA2StreamSystem570GetBroadcasterInfoV1GetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iDOTA2StreamSystem570GetBroadcasterInfoV1Get(requestParameters.broadcasterSteamId, requestParameters.leagueId, requestParameters.format, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for iDOTA2StreamSystem570GetBroadcasterInfoV1Get operation in IDOTA2StreamSystemApi.
 */
export interface IDOTA2StreamSystemApiIDOTA2StreamSystem570GetBroadcasterInfoV1GetRequest {
    /**
     * 64-bit Steam ID of the broadcaster
     */
    readonly broadcasterSteamId: number

    /**
     * LeagueID to use if we aren\&#39;t in a lobby
     */
    readonly leagueId?: number

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IDOTA2StreamSystem570GetBroadcasterInfoV1GetFormatEnum
}

/**
 * IDOTA2StreamSystemApi - object-oriented interface
 */
export class IDOTA2StreamSystemApi extends BaseAPI {
    /**
     * 
     * @param {IDOTA2StreamSystemApiIDOTA2StreamSystem570GetBroadcasterInfoV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iDOTA2StreamSystem570GetBroadcasterInfoV1Get(requestParameters: IDOTA2StreamSystemApiIDOTA2StreamSystem570GetBroadcasterInfoV1GetRequest, options?: RawAxiosRequestConfig) {
        return IDOTA2StreamSystemApiFp(this.configuration).iDOTA2StreamSystem570GetBroadcasterInfoV1Get(requestParameters.broadcasterSteamId, requestParameters.leagueId, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }
}

export const IDOTA2StreamSystem570GetBroadcasterInfoV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IDOTA2StreamSystem570GetBroadcasterInfoV1GetFormatEnum = typeof IDOTA2StreamSystem570GetBroadcasterInfoV1GetFormatEnum[keyof typeof IDOTA2StreamSystem570GetBroadcasterInfoV1GetFormatEnum];
