/* tslint:disable */
/* eslint-disable */
/**
 * Steamworks Web API
 * This is an OpenAPI specification for the Steamworks Web API. For more details on how to use this tool, check out the <a href=\"https://github.com/ceva24/openapi-steamworks-web-api/blob/main/README.md\">README</a>.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * IEconItemsApi - axios parameter creator
 */
export const IEconItemsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} steamid The Steam ID to fetch items for
         * @param {IEconItems1046930GetPlayerItemsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems1046930GetPlayerItemsV1Get: async (steamid: number, format?: IEconItems1046930GetPlayerItemsV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'steamid' is not null or undefined
            assertParamExists('iEconItems1046930GetPlayerItemsV1Get', 'steamid', steamid)
            const localVarPath = `/IEconItems_1046930/GetPlayerItems/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (steamid !== undefined) {
                localVarQueryParameter['steamid'] = steamid;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} steamid The Steam ID to fetch items for
         * @param {number} classId Return items equipped for this class id
         * @param {IEconItems1269260GetEquippedPlayerItemsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems1269260GetEquippedPlayerItemsV1Get: async (steamid: number, classId: number, format?: IEconItems1269260GetEquippedPlayerItemsV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'steamid' is not null or undefined
            assertParamExists('iEconItems1269260GetEquippedPlayerItemsV1Get', 'steamid', steamid)
            // verify required parameter 'classId' is not null or undefined
            assertParamExists('iEconItems1269260GetEquippedPlayerItemsV1Get', 'classId', classId)
            const localVarPath = `/IEconItems_1269260/GetEquippedPlayerItems/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (steamid !== undefined) {
                localVarQueryParameter['steamid'] = steamid;
            }

            if (classId !== undefined) {
                localVarQueryParameter['class_id'] = classId;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} steamid The Steam ID to fetch items for
         * @param {IEconItems238460GetPlayerItemsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems238460GetPlayerItemsV1Get: async (steamid: number, format?: IEconItems238460GetPlayerItemsV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'steamid' is not null or undefined
            assertParamExists('iEconItems238460GetPlayerItemsV1Get', 'steamid', steamid)
            const localVarPath = `/IEconItems_238460/GetPlayerItems/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (steamid !== undefined) {
                localVarQueryParameter['steamid'] = steamid;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} steamid The Steam ID to fetch items for
         * @param {IEconItems440GetPlayerItemsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems440GetPlayerItemsV1Get: async (steamid: number, format?: IEconItems440GetPlayerItemsV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'steamid' is not null or undefined
            assertParamExists('iEconItems440GetPlayerItemsV1Get', 'steamid', steamid)
            const localVarPath = `/IEconItems_440/GetPlayerItems/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (steamid !== undefined) {
                localVarQueryParameter['steamid'] = steamid;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [language] The language to return the names in. Defaults to returning string keys.
         * @param {number} [start] The first item id to return. Defaults to 0. Response will indicate next value to query if applicable.
         * @param {IEconItems440GetSchemaItemsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems440GetSchemaItemsV1Get: async (language?: string, start?: number, format?: IEconItems440GetSchemaItemsV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IEconItems_440/GetSchemaItems/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            if (start !== undefined) {
                localVarQueryParameter['start'] = start;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [language] The language to return the names in. Defaults to returning string keys.
         * @param {IEconItems440GetSchemaOverviewV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems440GetSchemaOverviewV1Get: async (language?: string, format?: IEconItems440GetSchemaOverviewV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IEconItems_440/GetSchemaOverview/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {IEconItems440GetSchemaURLV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems440GetSchemaURLV1Get: async (format?: IEconItems440GetSchemaURLV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IEconItems_440/GetSchemaURL/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [language] The language to return the names in. Defaults to returning string keys.
         * @param {IEconItems440GetSchemaV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems440GetSchemaV1Get: async (language?: string, format?: IEconItems440GetSchemaV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IEconItems_440/GetSchema/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [language] The language to results in.
         * @param {IEconItems440GetStoreMetaDataV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems440GetStoreMetaDataV1Get: async (language?: string, format?: IEconItems440GetStoreMetaDataV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IEconItems_440/GetStoreMetaData/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {IEconItems440GetStoreStatusV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems440GetStoreStatusV1Get: async (format?: IEconItems440GetStoreStatusV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IEconItems_440/GetStoreStatus/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} steamid The Steam ID to fetch items for
         * @param {IEconItems570GetPlayerItemsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems570GetPlayerItemsV1Get: async (steamid: number, format?: IEconItems570GetPlayerItemsV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'steamid' is not null or undefined
            assertParamExists('iEconItems570GetPlayerItemsV1Get', 'steamid', steamid)
            const localVarPath = `/IEconItems_570/GetPlayerItems/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (steamid !== undefined) {
                localVarQueryParameter['steamid'] = steamid;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [language] The language to results in.
         * @param {IEconItems570GetStoreMetaDataV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems570GetStoreMetaDataV1Get: async (language?: string, format?: IEconItems570GetStoreMetaDataV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IEconItems_570/GetStoreMetaData/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} steamid The Steam ID to fetch items for
         * @param {number} classId Return items equipped for this class id
         * @param {IEconItems583950GetEquippedPlayerItemsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems583950GetEquippedPlayerItemsV1Get: async (steamid: number, classId: number, format?: IEconItems583950GetEquippedPlayerItemsV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'steamid' is not null or undefined
            assertParamExists('iEconItems583950GetEquippedPlayerItemsV1Get', 'steamid', steamid)
            // verify required parameter 'classId' is not null or undefined
            assertParamExists('iEconItems583950GetEquippedPlayerItemsV1Get', 'classId', classId)
            const localVarPath = `/IEconItems_583950/GetEquippedPlayerItems/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (steamid !== undefined) {
                localVarQueryParameter['steamid'] = steamid;
            }

            if (classId !== undefined) {
                localVarQueryParameter['class_id'] = classId;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} steamid The Steam ID to fetch items for
         * @param {IEconItems620GetPlayerItemsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems620GetPlayerItemsV1Get: async (steamid: number, format?: IEconItems620GetPlayerItemsV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'steamid' is not null or undefined
            assertParamExists('iEconItems620GetPlayerItemsV1Get', 'steamid', steamid)
            const localVarPath = `/IEconItems_620/GetPlayerItems/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (steamid !== undefined) {
                localVarQueryParameter['steamid'] = steamid;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [language] The language to return the names in. Defaults to returning string keys.
         * @param {IEconItems620GetSchemaV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems620GetSchemaV1Get: async (language?: string, format?: IEconItems620GetSchemaV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IEconItems_620/GetSchema/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} steamid The Steam ID to fetch items for
         * @param {IEconItems730GetPlayerItemsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems730GetPlayerItemsV1Get: async (steamid: number, format?: IEconItems730GetPlayerItemsV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'steamid' is not null or undefined
            assertParamExists('iEconItems730GetPlayerItemsV1Get', 'steamid', steamid)
            const localVarPath = `/IEconItems_730/GetPlayerItems/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (steamid !== undefined) {
                localVarQueryParameter['steamid'] = steamid;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {IEconItems730GetSchemaURLV2GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems730GetSchemaURLV2Get: async (format?: IEconItems730GetSchemaURLV2GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IEconItems_730/GetSchemaURL/v2`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [language] The language to return the names in. Defaults to returning string keys.
         * @param {IEconItems730GetSchemaV2GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems730GetSchemaV2Get: async (language?: string, format?: IEconItems730GetSchemaV2GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IEconItems_730/GetSchema/v2`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [language] The language to results in.
         * @param {IEconItems730GetStoreMetaDataV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems730GetStoreMetaDataV1Get: async (language?: string, format?: IEconItems730GetStoreMetaDataV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IEconItems_730/GetStoreMetaData/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IEconItemsApi - functional programming interface
 */
export const IEconItemsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IEconItemsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} steamid The Steam ID to fetch items for
         * @param {IEconItems1046930GetPlayerItemsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iEconItems1046930GetPlayerItemsV1Get(steamid: number, format?: IEconItems1046930GetPlayerItemsV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iEconItems1046930GetPlayerItemsV1Get(steamid, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IEconItemsApi.iEconItems1046930GetPlayerItemsV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} steamid The Steam ID to fetch items for
         * @param {number} classId Return items equipped for this class id
         * @param {IEconItems1269260GetEquippedPlayerItemsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iEconItems1269260GetEquippedPlayerItemsV1Get(steamid: number, classId: number, format?: IEconItems1269260GetEquippedPlayerItemsV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iEconItems1269260GetEquippedPlayerItemsV1Get(steamid, classId, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IEconItemsApi.iEconItems1269260GetEquippedPlayerItemsV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} steamid The Steam ID to fetch items for
         * @param {IEconItems238460GetPlayerItemsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iEconItems238460GetPlayerItemsV1Get(steamid: number, format?: IEconItems238460GetPlayerItemsV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iEconItems238460GetPlayerItemsV1Get(steamid, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IEconItemsApi.iEconItems238460GetPlayerItemsV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} steamid The Steam ID to fetch items for
         * @param {IEconItems440GetPlayerItemsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iEconItems440GetPlayerItemsV1Get(steamid: number, format?: IEconItems440GetPlayerItemsV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iEconItems440GetPlayerItemsV1Get(steamid, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IEconItemsApi.iEconItems440GetPlayerItemsV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [language] The language to return the names in. Defaults to returning string keys.
         * @param {number} [start] The first item id to return. Defaults to 0. Response will indicate next value to query if applicable.
         * @param {IEconItems440GetSchemaItemsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iEconItems440GetSchemaItemsV1Get(language?: string, start?: number, format?: IEconItems440GetSchemaItemsV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iEconItems440GetSchemaItemsV1Get(language, start, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IEconItemsApi.iEconItems440GetSchemaItemsV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [language] The language to return the names in. Defaults to returning string keys.
         * @param {IEconItems440GetSchemaOverviewV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iEconItems440GetSchemaOverviewV1Get(language?: string, format?: IEconItems440GetSchemaOverviewV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iEconItems440GetSchemaOverviewV1Get(language, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IEconItemsApi.iEconItems440GetSchemaOverviewV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {IEconItems440GetSchemaURLV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iEconItems440GetSchemaURLV1Get(format?: IEconItems440GetSchemaURLV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iEconItems440GetSchemaURLV1Get(format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IEconItemsApi.iEconItems440GetSchemaURLV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [language] The language to return the names in. Defaults to returning string keys.
         * @param {IEconItems440GetSchemaV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iEconItems440GetSchemaV1Get(language?: string, format?: IEconItems440GetSchemaV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iEconItems440GetSchemaV1Get(language, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IEconItemsApi.iEconItems440GetSchemaV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [language] The language to results in.
         * @param {IEconItems440GetStoreMetaDataV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iEconItems440GetStoreMetaDataV1Get(language?: string, format?: IEconItems440GetStoreMetaDataV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iEconItems440GetStoreMetaDataV1Get(language, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IEconItemsApi.iEconItems440GetStoreMetaDataV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {IEconItems440GetStoreStatusV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iEconItems440GetStoreStatusV1Get(format?: IEconItems440GetStoreStatusV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iEconItems440GetStoreStatusV1Get(format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IEconItemsApi.iEconItems440GetStoreStatusV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} steamid The Steam ID to fetch items for
         * @param {IEconItems570GetPlayerItemsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iEconItems570GetPlayerItemsV1Get(steamid: number, format?: IEconItems570GetPlayerItemsV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iEconItems570GetPlayerItemsV1Get(steamid, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IEconItemsApi.iEconItems570GetPlayerItemsV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [language] The language to results in.
         * @param {IEconItems570GetStoreMetaDataV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iEconItems570GetStoreMetaDataV1Get(language?: string, format?: IEconItems570GetStoreMetaDataV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iEconItems570GetStoreMetaDataV1Get(language, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IEconItemsApi.iEconItems570GetStoreMetaDataV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} steamid The Steam ID to fetch items for
         * @param {number} classId Return items equipped for this class id
         * @param {IEconItems583950GetEquippedPlayerItemsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iEconItems583950GetEquippedPlayerItemsV1Get(steamid: number, classId: number, format?: IEconItems583950GetEquippedPlayerItemsV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iEconItems583950GetEquippedPlayerItemsV1Get(steamid, classId, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IEconItemsApi.iEconItems583950GetEquippedPlayerItemsV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} steamid The Steam ID to fetch items for
         * @param {IEconItems620GetPlayerItemsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iEconItems620GetPlayerItemsV1Get(steamid: number, format?: IEconItems620GetPlayerItemsV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iEconItems620GetPlayerItemsV1Get(steamid, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IEconItemsApi.iEconItems620GetPlayerItemsV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [language] The language to return the names in. Defaults to returning string keys.
         * @param {IEconItems620GetSchemaV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iEconItems620GetSchemaV1Get(language?: string, format?: IEconItems620GetSchemaV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iEconItems620GetSchemaV1Get(language, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IEconItemsApi.iEconItems620GetSchemaV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} steamid The Steam ID to fetch items for
         * @param {IEconItems730GetPlayerItemsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iEconItems730GetPlayerItemsV1Get(steamid: number, format?: IEconItems730GetPlayerItemsV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iEconItems730GetPlayerItemsV1Get(steamid, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IEconItemsApi.iEconItems730GetPlayerItemsV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {IEconItems730GetSchemaURLV2GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iEconItems730GetSchemaURLV2Get(format?: IEconItems730GetSchemaURLV2GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iEconItems730GetSchemaURLV2Get(format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IEconItemsApi.iEconItems730GetSchemaURLV2Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [language] The language to return the names in. Defaults to returning string keys.
         * @param {IEconItems730GetSchemaV2GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iEconItems730GetSchemaV2Get(language?: string, format?: IEconItems730GetSchemaV2GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iEconItems730GetSchemaV2Get(language, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IEconItemsApi.iEconItems730GetSchemaV2Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [language] The language to results in.
         * @param {IEconItems730GetStoreMetaDataV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iEconItems730GetStoreMetaDataV1Get(language?: string, format?: IEconItems730GetStoreMetaDataV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iEconItems730GetStoreMetaDataV1Get(language, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IEconItemsApi.iEconItems730GetStoreMetaDataV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * IEconItemsApi - factory interface
 */
export const IEconItemsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IEconItemsApiFp(configuration)
    return {
        /**
         * 
         * @param {IEconItemsApiIEconItems1046930GetPlayerItemsV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems1046930GetPlayerItemsV1Get(requestParameters: IEconItemsApiIEconItems1046930GetPlayerItemsV1GetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iEconItems1046930GetPlayerItemsV1Get(requestParameters.steamid, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IEconItemsApiIEconItems1269260GetEquippedPlayerItemsV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems1269260GetEquippedPlayerItemsV1Get(requestParameters: IEconItemsApiIEconItems1269260GetEquippedPlayerItemsV1GetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iEconItems1269260GetEquippedPlayerItemsV1Get(requestParameters.steamid, requestParameters.classId, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IEconItemsApiIEconItems238460GetPlayerItemsV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems238460GetPlayerItemsV1Get(requestParameters: IEconItemsApiIEconItems238460GetPlayerItemsV1GetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iEconItems238460GetPlayerItemsV1Get(requestParameters.steamid, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IEconItemsApiIEconItems440GetPlayerItemsV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems440GetPlayerItemsV1Get(requestParameters: IEconItemsApiIEconItems440GetPlayerItemsV1GetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iEconItems440GetPlayerItemsV1Get(requestParameters.steamid, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IEconItemsApiIEconItems440GetSchemaItemsV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems440GetSchemaItemsV1Get(requestParameters: IEconItemsApiIEconItems440GetSchemaItemsV1GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iEconItems440GetSchemaItemsV1Get(requestParameters.language, requestParameters.start, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IEconItemsApiIEconItems440GetSchemaOverviewV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems440GetSchemaOverviewV1Get(requestParameters: IEconItemsApiIEconItems440GetSchemaOverviewV1GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iEconItems440GetSchemaOverviewV1Get(requestParameters.language, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IEconItemsApiIEconItems440GetSchemaURLV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems440GetSchemaURLV1Get(requestParameters: IEconItemsApiIEconItems440GetSchemaURLV1GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iEconItems440GetSchemaURLV1Get(requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IEconItemsApiIEconItems440GetSchemaV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems440GetSchemaV1Get(requestParameters: IEconItemsApiIEconItems440GetSchemaV1GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iEconItems440GetSchemaV1Get(requestParameters.language, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IEconItemsApiIEconItems440GetStoreMetaDataV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems440GetStoreMetaDataV1Get(requestParameters: IEconItemsApiIEconItems440GetStoreMetaDataV1GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iEconItems440GetStoreMetaDataV1Get(requestParameters.language, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IEconItemsApiIEconItems440GetStoreStatusV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems440GetStoreStatusV1Get(requestParameters: IEconItemsApiIEconItems440GetStoreStatusV1GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iEconItems440GetStoreStatusV1Get(requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IEconItemsApiIEconItems570GetPlayerItemsV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems570GetPlayerItemsV1Get(requestParameters: IEconItemsApiIEconItems570GetPlayerItemsV1GetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iEconItems570GetPlayerItemsV1Get(requestParameters.steamid, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IEconItemsApiIEconItems570GetStoreMetaDataV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems570GetStoreMetaDataV1Get(requestParameters: IEconItemsApiIEconItems570GetStoreMetaDataV1GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iEconItems570GetStoreMetaDataV1Get(requestParameters.language, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IEconItemsApiIEconItems583950GetEquippedPlayerItemsV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems583950GetEquippedPlayerItemsV1Get(requestParameters: IEconItemsApiIEconItems583950GetEquippedPlayerItemsV1GetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iEconItems583950GetEquippedPlayerItemsV1Get(requestParameters.steamid, requestParameters.classId, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IEconItemsApiIEconItems620GetPlayerItemsV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems620GetPlayerItemsV1Get(requestParameters: IEconItemsApiIEconItems620GetPlayerItemsV1GetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iEconItems620GetPlayerItemsV1Get(requestParameters.steamid, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IEconItemsApiIEconItems620GetSchemaV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems620GetSchemaV1Get(requestParameters: IEconItemsApiIEconItems620GetSchemaV1GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iEconItems620GetSchemaV1Get(requestParameters.language, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IEconItemsApiIEconItems730GetPlayerItemsV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems730GetPlayerItemsV1Get(requestParameters: IEconItemsApiIEconItems730GetPlayerItemsV1GetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iEconItems730GetPlayerItemsV1Get(requestParameters.steamid, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IEconItemsApiIEconItems730GetSchemaURLV2GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems730GetSchemaURLV2Get(requestParameters: IEconItemsApiIEconItems730GetSchemaURLV2GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iEconItems730GetSchemaURLV2Get(requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IEconItemsApiIEconItems730GetSchemaV2GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems730GetSchemaV2Get(requestParameters: IEconItemsApiIEconItems730GetSchemaV2GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iEconItems730GetSchemaV2Get(requestParameters.language, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IEconItemsApiIEconItems730GetStoreMetaDataV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iEconItems730GetStoreMetaDataV1Get(requestParameters: IEconItemsApiIEconItems730GetStoreMetaDataV1GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iEconItems730GetStoreMetaDataV1Get(requestParameters.language, requestParameters.format, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for iEconItems1046930GetPlayerItemsV1Get operation in IEconItemsApi.
 */
export interface IEconItemsApiIEconItems1046930GetPlayerItemsV1GetRequest {
    /**
     * The Steam ID to fetch items for
     */
    readonly steamid: number

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IEconItems1046930GetPlayerItemsV1GetFormatEnum
}

/**
 * Request parameters for iEconItems1269260GetEquippedPlayerItemsV1Get operation in IEconItemsApi.
 */
export interface IEconItemsApiIEconItems1269260GetEquippedPlayerItemsV1GetRequest {
    /**
     * The Steam ID to fetch items for
     */
    readonly steamid: number

    /**
     * Return items equipped for this class id
     */
    readonly classId: number

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IEconItems1269260GetEquippedPlayerItemsV1GetFormatEnum
}

/**
 * Request parameters for iEconItems238460GetPlayerItemsV1Get operation in IEconItemsApi.
 */
export interface IEconItemsApiIEconItems238460GetPlayerItemsV1GetRequest {
    /**
     * The Steam ID to fetch items for
     */
    readonly steamid: number

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IEconItems238460GetPlayerItemsV1GetFormatEnum
}

/**
 * Request parameters for iEconItems440GetPlayerItemsV1Get operation in IEconItemsApi.
 */
export interface IEconItemsApiIEconItems440GetPlayerItemsV1GetRequest {
    /**
     * The Steam ID to fetch items for
     */
    readonly steamid: number

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IEconItems440GetPlayerItemsV1GetFormatEnum
}

/**
 * Request parameters for iEconItems440GetSchemaItemsV1Get operation in IEconItemsApi.
 */
export interface IEconItemsApiIEconItems440GetSchemaItemsV1GetRequest {
    /**
     * The language to return the names in. Defaults to returning string keys.
     */
    readonly language?: string

    /**
     * The first item id to return. Defaults to 0. Response will indicate next value to query if applicable.
     */
    readonly start?: number

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IEconItems440GetSchemaItemsV1GetFormatEnum
}

/**
 * Request parameters for iEconItems440GetSchemaOverviewV1Get operation in IEconItemsApi.
 */
export interface IEconItemsApiIEconItems440GetSchemaOverviewV1GetRequest {
    /**
     * The language to return the names in. Defaults to returning string keys.
     */
    readonly language?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IEconItems440GetSchemaOverviewV1GetFormatEnum
}

/**
 * Request parameters for iEconItems440GetSchemaURLV1Get operation in IEconItemsApi.
 */
export interface IEconItemsApiIEconItems440GetSchemaURLV1GetRequest {
    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IEconItems440GetSchemaURLV1GetFormatEnum
}

/**
 * Request parameters for iEconItems440GetSchemaV1Get operation in IEconItemsApi.
 */
export interface IEconItemsApiIEconItems440GetSchemaV1GetRequest {
    /**
     * The language to return the names in. Defaults to returning string keys.
     */
    readonly language?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IEconItems440GetSchemaV1GetFormatEnum
}

/**
 * Request parameters for iEconItems440GetStoreMetaDataV1Get operation in IEconItemsApi.
 */
export interface IEconItemsApiIEconItems440GetStoreMetaDataV1GetRequest {
    /**
     * The language to results in.
     */
    readonly language?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IEconItems440GetStoreMetaDataV1GetFormatEnum
}

/**
 * Request parameters for iEconItems440GetStoreStatusV1Get operation in IEconItemsApi.
 */
export interface IEconItemsApiIEconItems440GetStoreStatusV1GetRequest {
    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IEconItems440GetStoreStatusV1GetFormatEnum
}

/**
 * Request parameters for iEconItems570GetPlayerItemsV1Get operation in IEconItemsApi.
 */
export interface IEconItemsApiIEconItems570GetPlayerItemsV1GetRequest {
    /**
     * The Steam ID to fetch items for
     */
    readonly steamid: number

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IEconItems570GetPlayerItemsV1GetFormatEnum
}

/**
 * Request parameters for iEconItems570GetStoreMetaDataV1Get operation in IEconItemsApi.
 */
export interface IEconItemsApiIEconItems570GetStoreMetaDataV1GetRequest {
    /**
     * The language to results in.
     */
    readonly language?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IEconItems570GetStoreMetaDataV1GetFormatEnum
}

/**
 * Request parameters for iEconItems583950GetEquippedPlayerItemsV1Get operation in IEconItemsApi.
 */
export interface IEconItemsApiIEconItems583950GetEquippedPlayerItemsV1GetRequest {
    /**
     * The Steam ID to fetch items for
     */
    readonly steamid: number

    /**
     * Return items equipped for this class id
     */
    readonly classId: number

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IEconItems583950GetEquippedPlayerItemsV1GetFormatEnum
}

/**
 * Request parameters for iEconItems620GetPlayerItemsV1Get operation in IEconItemsApi.
 */
export interface IEconItemsApiIEconItems620GetPlayerItemsV1GetRequest {
    /**
     * The Steam ID to fetch items for
     */
    readonly steamid: number

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IEconItems620GetPlayerItemsV1GetFormatEnum
}

/**
 * Request parameters for iEconItems620GetSchemaV1Get operation in IEconItemsApi.
 */
export interface IEconItemsApiIEconItems620GetSchemaV1GetRequest {
    /**
     * The language to return the names in. Defaults to returning string keys.
     */
    readonly language?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IEconItems620GetSchemaV1GetFormatEnum
}

/**
 * Request parameters for iEconItems730GetPlayerItemsV1Get operation in IEconItemsApi.
 */
export interface IEconItemsApiIEconItems730GetPlayerItemsV1GetRequest {
    /**
     * The Steam ID to fetch items for
     */
    readonly steamid: number

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IEconItems730GetPlayerItemsV1GetFormatEnum
}

/**
 * Request parameters for iEconItems730GetSchemaURLV2Get operation in IEconItemsApi.
 */
export interface IEconItemsApiIEconItems730GetSchemaURLV2GetRequest {
    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IEconItems730GetSchemaURLV2GetFormatEnum
}

/**
 * Request parameters for iEconItems730GetSchemaV2Get operation in IEconItemsApi.
 */
export interface IEconItemsApiIEconItems730GetSchemaV2GetRequest {
    /**
     * The language to return the names in. Defaults to returning string keys.
     */
    readonly language?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IEconItems730GetSchemaV2GetFormatEnum
}

/**
 * Request parameters for iEconItems730GetStoreMetaDataV1Get operation in IEconItemsApi.
 */
export interface IEconItemsApiIEconItems730GetStoreMetaDataV1GetRequest {
    /**
     * The language to results in.
     */
    readonly language?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IEconItems730GetStoreMetaDataV1GetFormatEnum
}

/**
 * IEconItemsApi - object-oriented interface
 */
export class IEconItemsApi extends BaseAPI {
    /**
     * 
     * @param {IEconItemsApiIEconItems1046930GetPlayerItemsV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iEconItems1046930GetPlayerItemsV1Get(requestParameters: IEconItemsApiIEconItems1046930GetPlayerItemsV1GetRequest, options?: RawAxiosRequestConfig) {
        return IEconItemsApiFp(this.configuration).iEconItems1046930GetPlayerItemsV1Get(requestParameters.steamid, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IEconItemsApiIEconItems1269260GetEquippedPlayerItemsV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iEconItems1269260GetEquippedPlayerItemsV1Get(requestParameters: IEconItemsApiIEconItems1269260GetEquippedPlayerItemsV1GetRequest, options?: RawAxiosRequestConfig) {
        return IEconItemsApiFp(this.configuration).iEconItems1269260GetEquippedPlayerItemsV1Get(requestParameters.steamid, requestParameters.classId, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IEconItemsApiIEconItems238460GetPlayerItemsV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iEconItems238460GetPlayerItemsV1Get(requestParameters: IEconItemsApiIEconItems238460GetPlayerItemsV1GetRequest, options?: RawAxiosRequestConfig) {
        return IEconItemsApiFp(this.configuration).iEconItems238460GetPlayerItemsV1Get(requestParameters.steamid, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IEconItemsApiIEconItems440GetPlayerItemsV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iEconItems440GetPlayerItemsV1Get(requestParameters: IEconItemsApiIEconItems440GetPlayerItemsV1GetRequest, options?: RawAxiosRequestConfig) {
        return IEconItemsApiFp(this.configuration).iEconItems440GetPlayerItemsV1Get(requestParameters.steamid, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IEconItemsApiIEconItems440GetSchemaItemsV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iEconItems440GetSchemaItemsV1Get(requestParameters: IEconItemsApiIEconItems440GetSchemaItemsV1GetRequest = {}, options?: RawAxiosRequestConfig) {
        return IEconItemsApiFp(this.configuration).iEconItems440GetSchemaItemsV1Get(requestParameters.language, requestParameters.start, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IEconItemsApiIEconItems440GetSchemaOverviewV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iEconItems440GetSchemaOverviewV1Get(requestParameters: IEconItemsApiIEconItems440GetSchemaOverviewV1GetRequest = {}, options?: RawAxiosRequestConfig) {
        return IEconItemsApiFp(this.configuration).iEconItems440GetSchemaOverviewV1Get(requestParameters.language, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IEconItemsApiIEconItems440GetSchemaURLV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iEconItems440GetSchemaURLV1Get(requestParameters: IEconItemsApiIEconItems440GetSchemaURLV1GetRequest = {}, options?: RawAxiosRequestConfig) {
        return IEconItemsApiFp(this.configuration).iEconItems440GetSchemaURLV1Get(requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IEconItemsApiIEconItems440GetSchemaV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iEconItems440GetSchemaV1Get(requestParameters: IEconItemsApiIEconItems440GetSchemaV1GetRequest = {}, options?: RawAxiosRequestConfig) {
        return IEconItemsApiFp(this.configuration).iEconItems440GetSchemaV1Get(requestParameters.language, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IEconItemsApiIEconItems440GetStoreMetaDataV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iEconItems440GetStoreMetaDataV1Get(requestParameters: IEconItemsApiIEconItems440GetStoreMetaDataV1GetRequest = {}, options?: RawAxiosRequestConfig) {
        return IEconItemsApiFp(this.configuration).iEconItems440GetStoreMetaDataV1Get(requestParameters.language, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IEconItemsApiIEconItems440GetStoreStatusV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iEconItems440GetStoreStatusV1Get(requestParameters: IEconItemsApiIEconItems440GetStoreStatusV1GetRequest = {}, options?: RawAxiosRequestConfig) {
        return IEconItemsApiFp(this.configuration).iEconItems440GetStoreStatusV1Get(requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IEconItemsApiIEconItems570GetPlayerItemsV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iEconItems570GetPlayerItemsV1Get(requestParameters: IEconItemsApiIEconItems570GetPlayerItemsV1GetRequest, options?: RawAxiosRequestConfig) {
        return IEconItemsApiFp(this.configuration).iEconItems570GetPlayerItemsV1Get(requestParameters.steamid, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IEconItemsApiIEconItems570GetStoreMetaDataV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iEconItems570GetStoreMetaDataV1Get(requestParameters: IEconItemsApiIEconItems570GetStoreMetaDataV1GetRequest = {}, options?: RawAxiosRequestConfig) {
        return IEconItemsApiFp(this.configuration).iEconItems570GetStoreMetaDataV1Get(requestParameters.language, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IEconItemsApiIEconItems583950GetEquippedPlayerItemsV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iEconItems583950GetEquippedPlayerItemsV1Get(requestParameters: IEconItemsApiIEconItems583950GetEquippedPlayerItemsV1GetRequest, options?: RawAxiosRequestConfig) {
        return IEconItemsApiFp(this.configuration).iEconItems583950GetEquippedPlayerItemsV1Get(requestParameters.steamid, requestParameters.classId, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IEconItemsApiIEconItems620GetPlayerItemsV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iEconItems620GetPlayerItemsV1Get(requestParameters: IEconItemsApiIEconItems620GetPlayerItemsV1GetRequest, options?: RawAxiosRequestConfig) {
        return IEconItemsApiFp(this.configuration).iEconItems620GetPlayerItemsV1Get(requestParameters.steamid, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IEconItemsApiIEconItems620GetSchemaV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iEconItems620GetSchemaV1Get(requestParameters: IEconItemsApiIEconItems620GetSchemaV1GetRequest = {}, options?: RawAxiosRequestConfig) {
        return IEconItemsApiFp(this.configuration).iEconItems620GetSchemaV1Get(requestParameters.language, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IEconItemsApiIEconItems730GetPlayerItemsV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iEconItems730GetPlayerItemsV1Get(requestParameters: IEconItemsApiIEconItems730GetPlayerItemsV1GetRequest, options?: RawAxiosRequestConfig) {
        return IEconItemsApiFp(this.configuration).iEconItems730GetPlayerItemsV1Get(requestParameters.steamid, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IEconItemsApiIEconItems730GetSchemaURLV2GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iEconItems730GetSchemaURLV2Get(requestParameters: IEconItemsApiIEconItems730GetSchemaURLV2GetRequest = {}, options?: RawAxiosRequestConfig) {
        return IEconItemsApiFp(this.configuration).iEconItems730GetSchemaURLV2Get(requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IEconItemsApiIEconItems730GetSchemaV2GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iEconItems730GetSchemaV2Get(requestParameters: IEconItemsApiIEconItems730GetSchemaV2GetRequest = {}, options?: RawAxiosRequestConfig) {
        return IEconItemsApiFp(this.configuration).iEconItems730GetSchemaV2Get(requestParameters.language, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IEconItemsApiIEconItems730GetStoreMetaDataV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iEconItems730GetStoreMetaDataV1Get(requestParameters: IEconItemsApiIEconItems730GetStoreMetaDataV1GetRequest = {}, options?: RawAxiosRequestConfig) {
        return IEconItemsApiFp(this.configuration).iEconItems730GetStoreMetaDataV1Get(requestParameters.language, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }
}

export const IEconItems1046930GetPlayerItemsV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IEconItems1046930GetPlayerItemsV1GetFormatEnum = typeof IEconItems1046930GetPlayerItemsV1GetFormatEnum[keyof typeof IEconItems1046930GetPlayerItemsV1GetFormatEnum];
export const IEconItems1269260GetEquippedPlayerItemsV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IEconItems1269260GetEquippedPlayerItemsV1GetFormatEnum = typeof IEconItems1269260GetEquippedPlayerItemsV1GetFormatEnum[keyof typeof IEconItems1269260GetEquippedPlayerItemsV1GetFormatEnum];
export const IEconItems238460GetPlayerItemsV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IEconItems238460GetPlayerItemsV1GetFormatEnum = typeof IEconItems238460GetPlayerItemsV1GetFormatEnum[keyof typeof IEconItems238460GetPlayerItemsV1GetFormatEnum];
export const IEconItems440GetPlayerItemsV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IEconItems440GetPlayerItemsV1GetFormatEnum = typeof IEconItems440GetPlayerItemsV1GetFormatEnum[keyof typeof IEconItems440GetPlayerItemsV1GetFormatEnum];
export const IEconItems440GetSchemaItemsV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IEconItems440GetSchemaItemsV1GetFormatEnum = typeof IEconItems440GetSchemaItemsV1GetFormatEnum[keyof typeof IEconItems440GetSchemaItemsV1GetFormatEnum];
export const IEconItems440GetSchemaOverviewV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IEconItems440GetSchemaOverviewV1GetFormatEnum = typeof IEconItems440GetSchemaOverviewV1GetFormatEnum[keyof typeof IEconItems440GetSchemaOverviewV1GetFormatEnum];
export const IEconItems440GetSchemaURLV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IEconItems440GetSchemaURLV1GetFormatEnum = typeof IEconItems440GetSchemaURLV1GetFormatEnum[keyof typeof IEconItems440GetSchemaURLV1GetFormatEnum];
export const IEconItems440GetSchemaV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IEconItems440GetSchemaV1GetFormatEnum = typeof IEconItems440GetSchemaV1GetFormatEnum[keyof typeof IEconItems440GetSchemaV1GetFormatEnum];
export const IEconItems440GetStoreMetaDataV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IEconItems440GetStoreMetaDataV1GetFormatEnum = typeof IEconItems440GetStoreMetaDataV1GetFormatEnum[keyof typeof IEconItems440GetStoreMetaDataV1GetFormatEnum];
export const IEconItems440GetStoreStatusV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IEconItems440GetStoreStatusV1GetFormatEnum = typeof IEconItems440GetStoreStatusV1GetFormatEnum[keyof typeof IEconItems440GetStoreStatusV1GetFormatEnum];
export const IEconItems570GetPlayerItemsV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IEconItems570GetPlayerItemsV1GetFormatEnum = typeof IEconItems570GetPlayerItemsV1GetFormatEnum[keyof typeof IEconItems570GetPlayerItemsV1GetFormatEnum];
export const IEconItems570GetStoreMetaDataV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IEconItems570GetStoreMetaDataV1GetFormatEnum = typeof IEconItems570GetStoreMetaDataV1GetFormatEnum[keyof typeof IEconItems570GetStoreMetaDataV1GetFormatEnum];
export const IEconItems583950GetEquippedPlayerItemsV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IEconItems583950GetEquippedPlayerItemsV1GetFormatEnum = typeof IEconItems583950GetEquippedPlayerItemsV1GetFormatEnum[keyof typeof IEconItems583950GetEquippedPlayerItemsV1GetFormatEnum];
export const IEconItems620GetPlayerItemsV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IEconItems620GetPlayerItemsV1GetFormatEnum = typeof IEconItems620GetPlayerItemsV1GetFormatEnum[keyof typeof IEconItems620GetPlayerItemsV1GetFormatEnum];
export const IEconItems620GetSchemaV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IEconItems620GetSchemaV1GetFormatEnum = typeof IEconItems620GetSchemaV1GetFormatEnum[keyof typeof IEconItems620GetSchemaV1GetFormatEnum];
export const IEconItems730GetPlayerItemsV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IEconItems730GetPlayerItemsV1GetFormatEnum = typeof IEconItems730GetPlayerItemsV1GetFormatEnum[keyof typeof IEconItems730GetPlayerItemsV1GetFormatEnum];
export const IEconItems730GetSchemaURLV2GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IEconItems730GetSchemaURLV2GetFormatEnum = typeof IEconItems730GetSchemaURLV2GetFormatEnum[keyof typeof IEconItems730GetSchemaURLV2GetFormatEnum];
export const IEconItems730GetSchemaV2GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IEconItems730GetSchemaV2GetFormatEnum = typeof IEconItems730GetSchemaV2GetFormatEnum[keyof typeof IEconItems730GetSchemaV2GetFormatEnum];
export const IEconItems730GetStoreMetaDataV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IEconItems730GetStoreMetaDataV1GetFormatEnum = typeof IEconItems730GetStoreMetaDataV1GetFormatEnum[keyof typeof IEconItems730GetStoreMetaDataV1GetFormatEnum];
