/* tslint:disable */
/* eslint-disable */
/**
 * Steamworks Web API
 * This is an OpenAPI specification for the Steamworks Web API. For more details on how to use this tool, check out the <a href=\"https://github.com/ceva24/openapi-steamworks-web-api/blob/main/README.md\">README</a>.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * IGameNotificationsServiceApi - axios parameter creator
 */
export const IGameNotificationsServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IGameNotificationsServiceUserCreateSessionV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [appid] (Required) The appid to create the session for.
         * @param {number} [context] (Required) Game-specified context value the game can used to associate the session with some object on their backend.
         * @param {string} [title] (Required) The title of the session to be displayed within each user\\\&#39;s list of sessions.
         * @param {string} [users] (Required) The initial state of all users in the session.
         * @param {number} [steamid] (Optional) steamid to make the request on behalf of -- if specified, the user must be in the session and all users being added to the session must be friends with the user.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iGameNotificationsServiceUserCreateSessionV1Post: async (inputJson?: string, format?: IGameNotificationsServiceUserCreateSessionV1PostFormatEnum, appid?: number, context?: number, title?: string, users?: string, steamid?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IGameNotificationsService/UserCreateSession/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            if (appid !== undefined) { 
                localVarFormParams.set('appid', appid as any);
            }

            if (context !== undefined) { 
                localVarFormParams.set('context', context as any);
            }

            if (title !== undefined) { 
                localVarFormParams.set('title', title as any);
            }

            if (users !== undefined) { 
                localVarFormParams.set('users', users as any);
            }

            if (steamid !== undefined) { 
                localVarFormParams.set('steamid', steamid as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IGameNotificationsServiceUserDeleteSessionV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [sessionid] (Required) The sessionid to delete.
         * @param {number} [appid] (Required) The appid of the session to delete.
         * @param {number} [steamid] (Optional) steamid to make the request on behalf of -- if specified, the user must be in the session.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iGameNotificationsServiceUserDeleteSessionV1Post: async (inputJson?: string, format?: IGameNotificationsServiceUserDeleteSessionV1PostFormatEnum, sessionid?: number, appid?: number, steamid?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IGameNotificationsService/UserDeleteSession/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            if (sessionid !== undefined) { 
                localVarFormParams.set('sessionid', sessionid as any);
            }

            if (appid !== undefined) { 
                localVarFormParams.set('appid', appid as any);
            }

            if (steamid !== undefined) { 
                localVarFormParams.set('steamid', steamid as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IGameNotificationsServiceUserUpdateSessionV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [sessionid] (Required) The sessionid to update.
         * @param {number} [appid] (Required) The appid of the session to update.
         * @param {string} [title] (Optional) The new title of the session.  If not specified, the title will not be changed.
         * @param {string} [users] (Optional) A list of users whose state will be updated to reflect the given state. If the users are not already in the session, they will be added to it.
         * @param {number} [steamid] (Optional) steamid to make the request on behalf of -- if specified, the user must be in the session and all users being added to the session must be friends with the user.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iGameNotificationsServiceUserUpdateSessionV1Post: async (inputJson?: string, format?: IGameNotificationsServiceUserUpdateSessionV1PostFormatEnum, sessionid?: number, appid?: number, title?: string, users?: string, steamid?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IGameNotificationsService/UserUpdateSession/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            if (sessionid !== undefined) { 
                localVarFormParams.set('sessionid', sessionid as any);
            }

            if (appid !== undefined) { 
                localVarFormParams.set('appid', appid as any);
            }

            if (title !== undefined) { 
                localVarFormParams.set('title', title as any);
            }

            if (users !== undefined) { 
                localVarFormParams.set('users', users as any);
            }

            if (steamid !== undefined) { 
                localVarFormParams.set('steamid', steamid as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IGameNotificationsServiceApi - functional programming interface
 */
export const IGameNotificationsServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IGameNotificationsServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IGameNotificationsServiceUserCreateSessionV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [appid] (Required) The appid to create the session for.
         * @param {number} [context] (Required) Game-specified context value the game can used to associate the session with some object on their backend.
         * @param {string} [title] (Required) The title of the session to be displayed within each user\\\&#39;s list of sessions.
         * @param {string} [users] (Required) The initial state of all users in the session.
         * @param {number} [steamid] (Optional) steamid to make the request on behalf of -- if specified, the user must be in the session and all users being added to the session must be friends with the user.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iGameNotificationsServiceUserCreateSessionV1Post(inputJson?: string, format?: IGameNotificationsServiceUserCreateSessionV1PostFormatEnum, appid?: number, context?: number, title?: string, users?: string, steamid?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iGameNotificationsServiceUserCreateSessionV1Post(inputJson, format, appid, context, title, users, steamid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IGameNotificationsServiceApi.iGameNotificationsServiceUserCreateSessionV1Post']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IGameNotificationsServiceUserDeleteSessionV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [sessionid] (Required) The sessionid to delete.
         * @param {number} [appid] (Required) The appid of the session to delete.
         * @param {number} [steamid] (Optional) steamid to make the request on behalf of -- if specified, the user must be in the session.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iGameNotificationsServiceUserDeleteSessionV1Post(inputJson?: string, format?: IGameNotificationsServiceUserDeleteSessionV1PostFormatEnum, sessionid?: number, appid?: number, steamid?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iGameNotificationsServiceUserDeleteSessionV1Post(inputJson, format, sessionid, appid, steamid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IGameNotificationsServiceApi.iGameNotificationsServiceUserDeleteSessionV1Post']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IGameNotificationsServiceUserUpdateSessionV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [sessionid] (Required) The sessionid to update.
         * @param {number} [appid] (Required) The appid of the session to update.
         * @param {string} [title] (Optional) The new title of the session.  If not specified, the title will not be changed.
         * @param {string} [users] (Optional) A list of users whose state will be updated to reflect the given state. If the users are not already in the session, they will be added to it.
         * @param {number} [steamid] (Optional) steamid to make the request on behalf of -- if specified, the user must be in the session and all users being added to the session must be friends with the user.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iGameNotificationsServiceUserUpdateSessionV1Post(inputJson?: string, format?: IGameNotificationsServiceUserUpdateSessionV1PostFormatEnum, sessionid?: number, appid?: number, title?: string, users?: string, steamid?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iGameNotificationsServiceUserUpdateSessionV1Post(inputJson, format, sessionid, appid, title, users, steamid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IGameNotificationsServiceApi.iGameNotificationsServiceUserUpdateSessionV1Post']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * IGameNotificationsServiceApi - factory interface
 */
export const IGameNotificationsServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IGameNotificationsServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {IGameNotificationsServiceApiIGameNotificationsServiceUserCreateSessionV1PostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iGameNotificationsServiceUserCreateSessionV1Post(requestParameters: IGameNotificationsServiceApiIGameNotificationsServiceUserCreateSessionV1PostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iGameNotificationsServiceUserCreateSessionV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.appid, requestParameters.context, requestParameters.title, requestParameters.users, requestParameters.steamid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IGameNotificationsServiceApiIGameNotificationsServiceUserDeleteSessionV1PostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iGameNotificationsServiceUserDeleteSessionV1Post(requestParameters: IGameNotificationsServiceApiIGameNotificationsServiceUserDeleteSessionV1PostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iGameNotificationsServiceUserDeleteSessionV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.sessionid, requestParameters.appid, requestParameters.steamid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IGameNotificationsServiceApiIGameNotificationsServiceUserUpdateSessionV1PostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iGameNotificationsServiceUserUpdateSessionV1Post(requestParameters: IGameNotificationsServiceApiIGameNotificationsServiceUserUpdateSessionV1PostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iGameNotificationsServiceUserUpdateSessionV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.sessionid, requestParameters.appid, requestParameters.title, requestParameters.users, requestParameters.steamid, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for iGameNotificationsServiceUserCreateSessionV1Post operation in IGameNotificationsServiceApi.
 */
export interface IGameNotificationsServiceApiIGameNotificationsServiceUserCreateSessionV1PostRequest {
    /**
     * An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IGameNotificationsServiceUserCreateSessionV1PostFormatEnum

    /**
     * (Required) The appid to create the session for.
     */
    readonly appid?: number

    /**
     * (Required) Game-specified context value the game can used to associate the session with some object on their backend.
     */
    readonly context?: number

    /**
     * (Required) The title of the session to be displayed within each user\\\&#39;s list of sessions.
     */
    readonly title?: string

    /**
     * (Required) The initial state of all users in the session.
     */
    readonly users?: string

    /**
     * (Optional) steamid to make the request on behalf of -- if specified, the user must be in the session and all users being added to the session must be friends with the user.
     */
    readonly steamid?: number
}

/**
 * Request parameters for iGameNotificationsServiceUserDeleteSessionV1Post operation in IGameNotificationsServiceApi.
 */
export interface IGameNotificationsServiceApiIGameNotificationsServiceUserDeleteSessionV1PostRequest {
    /**
     * An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IGameNotificationsServiceUserDeleteSessionV1PostFormatEnum

    /**
     * (Required) The sessionid to delete.
     */
    readonly sessionid?: number

    /**
     * (Required) The appid of the session to delete.
     */
    readonly appid?: number

    /**
     * (Optional) steamid to make the request on behalf of -- if specified, the user must be in the session.
     */
    readonly steamid?: number
}

/**
 * Request parameters for iGameNotificationsServiceUserUpdateSessionV1Post operation in IGameNotificationsServiceApi.
 */
export interface IGameNotificationsServiceApiIGameNotificationsServiceUserUpdateSessionV1PostRequest {
    /**
     * An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IGameNotificationsServiceUserUpdateSessionV1PostFormatEnum

    /**
     * (Required) The sessionid to update.
     */
    readonly sessionid?: number

    /**
     * (Required) The appid of the session to update.
     */
    readonly appid?: number

    /**
     * (Optional) The new title of the session.  If not specified, the title will not be changed.
     */
    readonly title?: string

    /**
     * (Optional) A list of users whose state will be updated to reflect the given state. If the users are not already in the session, they will be added to it.
     */
    readonly users?: string

    /**
     * (Optional) steamid to make the request on behalf of -- if specified, the user must be in the session and all users being added to the session must be friends with the user.
     */
    readonly steamid?: number
}

/**
 * IGameNotificationsServiceApi - object-oriented interface
 */
export class IGameNotificationsServiceApi extends BaseAPI {
    /**
     * 
     * @param {IGameNotificationsServiceApiIGameNotificationsServiceUserCreateSessionV1PostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iGameNotificationsServiceUserCreateSessionV1Post(requestParameters: IGameNotificationsServiceApiIGameNotificationsServiceUserCreateSessionV1PostRequest = {}, options?: RawAxiosRequestConfig) {
        return IGameNotificationsServiceApiFp(this.configuration).iGameNotificationsServiceUserCreateSessionV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.appid, requestParameters.context, requestParameters.title, requestParameters.users, requestParameters.steamid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IGameNotificationsServiceApiIGameNotificationsServiceUserDeleteSessionV1PostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iGameNotificationsServiceUserDeleteSessionV1Post(requestParameters: IGameNotificationsServiceApiIGameNotificationsServiceUserDeleteSessionV1PostRequest = {}, options?: RawAxiosRequestConfig) {
        return IGameNotificationsServiceApiFp(this.configuration).iGameNotificationsServiceUserDeleteSessionV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.sessionid, requestParameters.appid, requestParameters.steamid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IGameNotificationsServiceApiIGameNotificationsServiceUserUpdateSessionV1PostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iGameNotificationsServiceUserUpdateSessionV1Post(requestParameters: IGameNotificationsServiceApiIGameNotificationsServiceUserUpdateSessionV1PostRequest = {}, options?: RawAxiosRequestConfig) {
        return IGameNotificationsServiceApiFp(this.configuration).iGameNotificationsServiceUserUpdateSessionV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.sessionid, requestParameters.appid, requestParameters.title, requestParameters.users, requestParameters.steamid, options).then((request) => request(this.axios, this.basePath));
    }
}

export const IGameNotificationsServiceUserCreateSessionV1PostFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IGameNotificationsServiceUserCreateSessionV1PostFormatEnum = typeof IGameNotificationsServiceUserCreateSessionV1PostFormatEnum[keyof typeof IGameNotificationsServiceUserCreateSessionV1PostFormatEnum];
export const IGameNotificationsServiceUserDeleteSessionV1PostFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IGameNotificationsServiceUserDeleteSessionV1PostFormatEnum = typeof IGameNotificationsServiceUserDeleteSessionV1PostFormatEnum[keyof typeof IGameNotificationsServiceUserDeleteSessionV1PostFormatEnum];
export const IGameNotificationsServiceUserUpdateSessionV1PostFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IGameNotificationsServiceUserUpdateSessionV1PostFormatEnum = typeof IGameNotificationsServiceUserUpdateSessionV1PostFormatEnum[keyof typeof IGameNotificationsServiceUserUpdateSessionV1PostFormatEnum];
