/* tslint:disable */
/* eslint-disable */
/**
 * Steamworks Web API
 * This is an OpenAPI specification for the Steamworks Web API. For more details on how to use this tool, check out the <a href=\"https://github.com/ceva24/openapi-steamworks-web-api/blob/main/README.md\">README</a>.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * IHelpRequestLogsServiceApi - axios parameter creator
 */
export const IHelpRequestLogsServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IHelpRequestLogsServiceGetApplicationLogDemandV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [appid] (Required)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iHelpRequestLogsServiceGetApplicationLogDemandV1Post: async (inputJson?: string, format?: IHelpRequestLogsServiceGetApplicationLogDemandV1PostFormatEnum, appid?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IHelpRequestLogsService/GetApplicationLogDemand/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            if (appid !== undefined) { 
                localVarFormParams.set('appid', appid as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IHelpRequestLogsServiceUploadUserApplicationLogV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [appid] (Required)
         * @param {string} [logType] (Required)
         * @param {string} [versionString] (Required)
         * @param {string} [logContents] (Required)
         * @param {number} [requestId] (Required)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iHelpRequestLogsServiceUploadUserApplicationLogV1Post: async (inputJson?: string, format?: IHelpRequestLogsServiceUploadUserApplicationLogV1PostFormatEnum, appid?: number, logType?: string, versionString?: string, logContents?: string, requestId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IHelpRequestLogsService/UploadUserApplicationLog/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            if (appid !== undefined) { 
                localVarFormParams.set('appid', appid as any);
            }

            if (logType !== undefined) { 
                localVarFormParams.set('log_type', logType as any);
            }

            if (versionString !== undefined) { 
                localVarFormParams.set('version_string', versionString as any);
            }

            if (logContents !== undefined) { 
                localVarFormParams.set('log_contents', logContents as any);
            }

            if (requestId !== undefined) { 
                localVarFormParams.set('request_id', requestId as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IHelpRequestLogsServiceApi - functional programming interface
 */
export const IHelpRequestLogsServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IHelpRequestLogsServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IHelpRequestLogsServiceGetApplicationLogDemandV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [appid] (Required)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iHelpRequestLogsServiceGetApplicationLogDemandV1Post(inputJson?: string, format?: IHelpRequestLogsServiceGetApplicationLogDemandV1PostFormatEnum, appid?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iHelpRequestLogsServiceGetApplicationLogDemandV1Post(inputJson, format, appid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IHelpRequestLogsServiceApi.iHelpRequestLogsServiceGetApplicationLogDemandV1Post']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IHelpRequestLogsServiceUploadUserApplicationLogV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [appid] (Required)
         * @param {string} [logType] (Required)
         * @param {string} [versionString] (Required)
         * @param {string} [logContents] (Required)
         * @param {number} [requestId] (Required)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iHelpRequestLogsServiceUploadUserApplicationLogV1Post(inputJson?: string, format?: IHelpRequestLogsServiceUploadUserApplicationLogV1PostFormatEnum, appid?: number, logType?: string, versionString?: string, logContents?: string, requestId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iHelpRequestLogsServiceUploadUserApplicationLogV1Post(inputJson, format, appid, logType, versionString, logContents, requestId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IHelpRequestLogsServiceApi.iHelpRequestLogsServiceUploadUserApplicationLogV1Post']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * IHelpRequestLogsServiceApi - factory interface
 */
export const IHelpRequestLogsServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IHelpRequestLogsServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {IHelpRequestLogsServiceApiIHelpRequestLogsServiceGetApplicationLogDemandV1PostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iHelpRequestLogsServiceGetApplicationLogDemandV1Post(requestParameters: IHelpRequestLogsServiceApiIHelpRequestLogsServiceGetApplicationLogDemandV1PostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iHelpRequestLogsServiceGetApplicationLogDemandV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.appid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IHelpRequestLogsServiceApiIHelpRequestLogsServiceUploadUserApplicationLogV1PostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iHelpRequestLogsServiceUploadUserApplicationLogV1Post(requestParameters: IHelpRequestLogsServiceApiIHelpRequestLogsServiceUploadUserApplicationLogV1PostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iHelpRequestLogsServiceUploadUserApplicationLogV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.appid, requestParameters.logType, requestParameters.versionString, requestParameters.logContents, requestParameters.requestId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for iHelpRequestLogsServiceGetApplicationLogDemandV1Post operation in IHelpRequestLogsServiceApi.
 */
export interface IHelpRequestLogsServiceApiIHelpRequestLogsServiceGetApplicationLogDemandV1PostRequest {
    /**
     * An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IHelpRequestLogsServiceGetApplicationLogDemandV1PostFormatEnum

    /**
     * (Required)
     */
    readonly appid?: number
}

/**
 * Request parameters for iHelpRequestLogsServiceUploadUserApplicationLogV1Post operation in IHelpRequestLogsServiceApi.
 */
export interface IHelpRequestLogsServiceApiIHelpRequestLogsServiceUploadUserApplicationLogV1PostRequest {
    /**
     * An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IHelpRequestLogsServiceUploadUserApplicationLogV1PostFormatEnum

    /**
     * (Required)
     */
    readonly appid?: number

    /**
     * (Required)
     */
    readonly logType?: string

    /**
     * (Required)
     */
    readonly versionString?: string

    /**
     * (Required)
     */
    readonly logContents?: string

    /**
     * (Required)
     */
    readonly requestId?: number
}

/**
 * IHelpRequestLogsServiceApi - object-oriented interface
 */
export class IHelpRequestLogsServiceApi extends BaseAPI {
    /**
     * 
     * @param {IHelpRequestLogsServiceApiIHelpRequestLogsServiceGetApplicationLogDemandV1PostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iHelpRequestLogsServiceGetApplicationLogDemandV1Post(requestParameters: IHelpRequestLogsServiceApiIHelpRequestLogsServiceGetApplicationLogDemandV1PostRequest = {}, options?: RawAxiosRequestConfig) {
        return IHelpRequestLogsServiceApiFp(this.configuration).iHelpRequestLogsServiceGetApplicationLogDemandV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.appid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IHelpRequestLogsServiceApiIHelpRequestLogsServiceUploadUserApplicationLogV1PostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iHelpRequestLogsServiceUploadUserApplicationLogV1Post(requestParameters: IHelpRequestLogsServiceApiIHelpRequestLogsServiceUploadUserApplicationLogV1PostRequest = {}, options?: RawAxiosRequestConfig) {
        return IHelpRequestLogsServiceApiFp(this.configuration).iHelpRequestLogsServiceUploadUserApplicationLogV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.appid, requestParameters.logType, requestParameters.versionString, requestParameters.logContents, requestParameters.requestId, options).then((request) => request(this.axios, this.basePath));
    }
}

export const IHelpRequestLogsServiceGetApplicationLogDemandV1PostFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IHelpRequestLogsServiceGetApplicationLogDemandV1PostFormatEnum = typeof IHelpRequestLogsServiceGetApplicationLogDemandV1PostFormatEnum[keyof typeof IHelpRequestLogsServiceGetApplicationLogDemandV1PostFormatEnum];
export const IHelpRequestLogsServiceUploadUserApplicationLogV1PostFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IHelpRequestLogsServiceUploadUserApplicationLogV1PostFormatEnum = typeof IHelpRequestLogsServiceUploadUserApplicationLogV1PostFormatEnum[keyof typeof IHelpRequestLogsServiceUploadUserApplicationLogV1PostFormatEnum];
