/* tslint:disable */
/* eslint-disable */
/**
 * Steamworks Web API
 * This is an OpenAPI specification for the Steamworks Web API. For more details on how to use this tool, check out the <a href=\"https://github.com/ceva24/openapi-steamworks-web-api/blob/main/README.md\">README</a>.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * IInventoryServiceApi - axios parameter creator
 */
export const IInventoryServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IInventoryServiceCombineItemStacksV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [appid] (Required)
         * @param {number} [fromitemid] (Required)
         * @param {number} [destitemid] (Required)
         * @param {number} [quantity] (Required)
         * @param {number} [steamid] (Required)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iInventoryServiceCombineItemStacksV1Post: async (inputJson?: string, format?: IInventoryServiceCombineItemStacksV1PostFormatEnum, appid?: number, fromitemid?: number, destitemid?: number, quantity?: number, steamid?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IInventoryService/CombineItemStacks/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            if (appid !== undefined) { 
                localVarFormParams.set('appid', appid as any);
            }

            if (fromitemid !== undefined) { 
                localVarFormParams.set('fromitemid', fromitemid as any);
            }

            if (destitemid !== undefined) { 
                localVarFormParams.set('destitemid', destitemid as any);
            }

            if (quantity !== undefined) { 
                localVarFormParams.set('quantity', quantity as any);
            }

            if (steamid !== undefined) { 
                localVarFormParams.set('steamid', steamid as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [ecurrency] (Required)
         * @param {string} [currencyCode] (Required) Standard short code of the requested currency (preferred)
         * @param {string} [inputJson] An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IInventoryServiceGetPriceSheetV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iInventoryServiceGetPriceSheetV1Get: async (ecurrency?: number, currencyCode?: string, inputJson?: string, format?: IInventoryServiceGetPriceSheetV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IInventoryService/GetPriceSheet/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (ecurrency !== undefined) {
                localVarQueryParameter['ecurrency'] = ecurrency;
            }

            if (currencyCode !== undefined) {
                localVarQueryParameter['currency_code'] = currencyCode;
            }

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IInventoryServiceSplitItemStackV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [appid] (Required)
         * @param {number} [itemid] (Required)
         * @param {number} [quantity] (Required)
         * @param {number} [steamid] (Required)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iInventoryServiceSplitItemStackV1Post: async (inputJson?: string, format?: IInventoryServiceSplitItemStackV1PostFormatEnum, appid?: number, itemid?: number, quantity?: number, steamid?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IInventoryService/SplitItemStack/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            if (appid !== undefined) { 
                localVarFormParams.set('appid', appid as any);
            }

            if (itemid !== undefined) { 
                localVarFormParams.set('itemid', itemid as any);
            }

            if (quantity !== undefined) { 
                localVarFormParams.set('quantity', quantity as any);
            }

            if (steamid !== undefined) { 
                localVarFormParams.set('steamid', steamid as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IInventoryServiceApi - functional programming interface
 */
export const IInventoryServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IInventoryServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IInventoryServiceCombineItemStacksV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [appid] (Required)
         * @param {number} [fromitemid] (Required)
         * @param {number} [destitemid] (Required)
         * @param {number} [quantity] (Required)
         * @param {number} [steamid] (Required)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iInventoryServiceCombineItemStacksV1Post(inputJson?: string, format?: IInventoryServiceCombineItemStacksV1PostFormatEnum, appid?: number, fromitemid?: number, destitemid?: number, quantity?: number, steamid?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iInventoryServiceCombineItemStacksV1Post(inputJson, format, appid, fromitemid, destitemid, quantity, steamid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IInventoryServiceApi.iInventoryServiceCombineItemStacksV1Post']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [ecurrency] (Required)
         * @param {string} [currencyCode] (Required) Standard short code of the requested currency (preferred)
         * @param {string} [inputJson] An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IInventoryServiceGetPriceSheetV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iInventoryServiceGetPriceSheetV1Get(ecurrency?: number, currencyCode?: string, inputJson?: string, format?: IInventoryServiceGetPriceSheetV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iInventoryServiceGetPriceSheetV1Get(ecurrency, currencyCode, inputJson, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IInventoryServiceApi.iInventoryServiceGetPriceSheetV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [inputJson] An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IInventoryServiceSplitItemStackV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [appid] (Required)
         * @param {number} [itemid] (Required)
         * @param {number} [quantity] (Required)
         * @param {number} [steamid] (Required)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iInventoryServiceSplitItemStackV1Post(inputJson?: string, format?: IInventoryServiceSplitItemStackV1PostFormatEnum, appid?: number, itemid?: number, quantity?: number, steamid?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iInventoryServiceSplitItemStackV1Post(inputJson, format, appid, itemid, quantity, steamid, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IInventoryServiceApi.iInventoryServiceSplitItemStackV1Post']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * IInventoryServiceApi - factory interface
 */
export const IInventoryServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IInventoryServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {IInventoryServiceApiIInventoryServiceCombineItemStacksV1PostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iInventoryServiceCombineItemStacksV1Post(requestParameters: IInventoryServiceApiIInventoryServiceCombineItemStacksV1PostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iInventoryServiceCombineItemStacksV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.appid, requestParameters.fromitemid, requestParameters.destitemid, requestParameters.quantity, requestParameters.steamid, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IInventoryServiceApiIInventoryServiceGetPriceSheetV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iInventoryServiceGetPriceSheetV1Get(requestParameters: IInventoryServiceApiIInventoryServiceGetPriceSheetV1GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iInventoryServiceGetPriceSheetV1Get(requestParameters.ecurrency, requestParameters.currencyCode, requestParameters.inputJson, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IInventoryServiceApiIInventoryServiceSplitItemStackV1PostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iInventoryServiceSplitItemStackV1Post(requestParameters: IInventoryServiceApiIInventoryServiceSplitItemStackV1PostRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iInventoryServiceSplitItemStackV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.appid, requestParameters.itemid, requestParameters.quantity, requestParameters.steamid, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for iInventoryServiceCombineItemStacksV1Post operation in IInventoryServiceApi.
 */
export interface IInventoryServiceApiIInventoryServiceCombineItemStacksV1PostRequest {
    /**
     * An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IInventoryServiceCombineItemStacksV1PostFormatEnum

    /**
     * (Required)
     */
    readonly appid?: number

    /**
     * (Required)
     */
    readonly fromitemid?: number

    /**
     * (Required)
     */
    readonly destitemid?: number

    /**
     * (Required)
     */
    readonly quantity?: number

    /**
     * (Required)
     */
    readonly steamid?: number
}

/**
 * Request parameters for iInventoryServiceGetPriceSheetV1Get operation in IInventoryServiceApi.
 */
export interface IInventoryServiceApiIInventoryServiceGetPriceSheetV1GetRequest {
    /**
     * (Required)
     */
    readonly ecurrency?: number

    /**
     * (Required) Standard short code of the requested currency (preferred)
     */
    readonly currencyCode?: string

    /**
     * An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IInventoryServiceGetPriceSheetV1GetFormatEnum
}

/**
 * Request parameters for iInventoryServiceSplitItemStackV1Post operation in IInventoryServiceApi.
 */
export interface IInventoryServiceApiIInventoryServiceSplitItemStackV1PostRequest {
    /**
     * An alternative to the request body; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IInventoryServiceSplitItemStackV1PostFormatEnum

    /**
     * (Required)
     */
    readonly appid?: number

    /**
     * (Required)
     */
    readonly itemid?: number

    /**
     * (Required)
     */
    readonly quantity?: number

    /**
     * (Required)
     */
    readonly steamid?: number
}

/**
 * IInventoryServiceApi - object-oriented interface
 */
export class IInventoryServiceApi extends BaseAPI {
    /**
     * 
     * @param {IInventoryServiceApiIInventoryServiceCombineItemStacksV1PostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iInventoryServiceCombineItemStacksV1Post(requestParameters: IInventoryServiceApiIInventoryServiceCombineItemStacksV1PostRequest = {}, options?: RawAxiosRequestConfig) {
        return IInventoryServiceApiFp(this.configuration).iInventoryServiceCombineItemStacksV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.appid, requestParameters.fromitemid, requestParameters.destitemid, requestParameters.quantity, requestParameters.steamid, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IInventoryServiceApiIInventoryServiceGetPriceSheetV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iInventoryServiceGetPriceSheetV1Get(requestParameters: IInventoryServiceApiIInventoryServiceGetPriceSheetV1GetRequest = {}, options?: RawAxiosRequestConfig) {
        return IInventoryServiceApiFp(this.configuration).iInventoryServiceGetPriceSheetV1Get(requestParameters.ecurrency, requestParameters.currencyCode, requestParameters.inputJson, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IInventoryServiceApiIInventoryServiceSplitItemStackV1PostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iInventoryServiceSplitItemStackV1Post(requestParameters: IInventoryServiceApiIInventoryServiceSplitItemStackV1PostRequest = {}, options?: RawAxiosRequestConfig) {
        return IInventoryServiceApiFp(this.configuration).iInventoryServiceSplitItemStackV1Post(requestParameters.inputJson, requestParameters.format, requestParameters.appid, requestParameters.itemid, requestParameters.quantity, requestParameters.steamid, options).then((request) => request(this.axios, this.basePath));
    }
}

export const IInventoryServiceCombineItemStacksV1PostFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IInventoryServiceCombineItemStacksV1PostFormatEnum = typeof IInventoryServiceCombineItemStacksV1PostFormatEnum[keyof typeof IInventoryServiceCombineItemStacksV1PostFormatEnum];
export const IInventoryServiceGetPriceSheetV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IInventoryServiceGetPriceSheetV1GetFormatEnum = typeof IInventoryServiceGetPriceSheetV1GetFormatEnum[keyof typeof IInventoryServiceGetPriceSheetV1GetFormatEnum];
export const IInventoryServiceSplitItemStackV1PostFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IInventoryServiceSplitItemStackV1PostFormatEnum = typeof IInventoryServiceSplitItemStackV1PostFormatEnum[keyof typeof IInventoryServiceSplitItemStackV1PostFormatEnum];
