/* tslint:disable */
/* eslint-disable */
/**
 * Steamworks Web API
 * This is an OpenAPI specification for the Steamworks Web API. For more details on how to use this tool, check out the <a href=\"https://github.com/ceva24/openapi-steamworks-web-api/blob/main/README.md\">README</a>.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * IPortal2LeaderboardsApi - axios parameter creator
 */
export const IPortal2LeaderboardsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} leaderboardName The leaderboard name to fetch data for.
         * @param {IPortal2Leaderboards620GetBucketizedDataV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iPortal2Leaderboards620GetBucketizedDataV1Get: async (leaderboardName: string, format?: IPortal2Leaderboards620GetBucketizedDataV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'leaderboardName' is not null or undefined
            assertParamExists('iPortal2Leaderboards620GetBucketizedDataV1Get', 'leaderboardName', leaderboardName)
            const localVarPath = `/IPortal2Leaderboards_620/GetBucketizedData/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (leaderboardName !== undefined) {
                localVarQueryParameter['leaderboardName'] = leaderboardName;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IPortal2LeaderboardsApi - functional programming interface
 */
export const IPortal2LeaderboardsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IPortal2LeaderboardsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} leaderboardName The leaderboard name to fetch data for.
         * @param {IPortal2Leaderboards620GetBucketizedDataV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iPortal2Leaderboards620GetBucketizedDataV1Get(leaderboardName: string, format?: IPortal2Leaderboards620GetBucketizedDataV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iPortal2Leaderboards620GetBucketizedDataV1Get(leaderboardName, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IPortal2LeaderboardsApi.iPortal2Leaderboards620GetBucketizedDataV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * IPortal2LeaderboardsApi - factory interface
 */
export const IPortal2LeaderboardsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IPortal2LeaderboardsApiFp(configuration)
    return {
        /**
         * 
         * @param {IPortal2LeaderboardsApiIPortal2Leaderboards620GetBucketizedDataV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iPortal2Leaderboards620GetBucketizedDataV1Get(requestParameters: IPortal2LeaderboardsApiIPortal2Leaderboards620GetBucketizedDataV1GetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iPortal2Leaderboards620GetBucketizedDataV1Get(requestParameters.leaderboardName, requestParameters.format, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for iPortal2Leaderboards620GetBucketizedDataV1Get operation in IPortal2LeaderboardsApi.
 */
export interface IPortal2LeaderboardsApiIPortal2Leaderboards620GetBucketizedDataV1GetRequest {
    /**
     * The leaderboard name to fetch data for.
     */
    readonly leaderboardName: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IPortal2Leaderboards620GetBucketizedDataV1GetFormatEnum
}

/**
 * IPortal2LeaderboardsApi - object-oriented interface
 */
export class IPortal2LeaderboardsApi extends BaseAPI {
    /**
     * 
     * @param {IPortal2LeaderboardsApiIPortal2Leaderboards620GetBucketizedDataV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iPortal2Leaderboards620GetBucketizedDataV1Get(requestParameters: IPortal2LeaderboardsApiIPortal2Leaderboards620GetBucketizedDataV1GetRequest, options?: RawAxiosRequestConfig) {
        return IPortal2LeaderboardsApiFp(this.configuration).iPortal2Leaderboards620GetBucketizedDataV1Get(requestParameters.leaderboardName, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }
}

export const IPortal2Leaderboards620GetBucketizedDataV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IPortal2Leaderboards620GetBucketizedDataV1GetFormatEnum = typeof IPortal2Leaderboards620GetBucketizedDataV1GetFormatEnum[keyof typeof IPortal2Leaderboards620GetBucketizedDataV1GetFormatEnum];
