/* tslint:disable */
/* eslint-disable */
/**
 * Steamworks Web API
 * This is an OpenAPI specification for the Steamworks Web API. For more details on how to use this tool, check out the <a href=\"https://github.com/ceva24/openapi-steamworks-web-api/blob/main/README.md\">README</a>.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * ISteamDirectoryApi - axios parameter creator
 */
export const ISteamDirectoryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} [cellid] Client\&#39;s Steam cell ID, uses IP location if blank
         * @param {string} [cmtype] Optional CM type filter
         * @param {string} [realm] Optional Steam Realm filter
         * @param {number} [maxcount] Max number of servers to return
         * @param {number} [qoslevel] Desired connection priority
         * @param {ISteamDirectoryGetCMListForConnectV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iSteamDirectoryGetCMListForConnectV1Get: async (cellid?: number, cmtype?: string, realm?: string, maxcount?: number, qoslevel?: number, format?: ISteamDirectoryGetCMListForConnectV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ISteamDirectory/GetCMListForConnect/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (cellid !== undefined) {
                localVarQueryParameter['cellid'] = cellid;
            }

            if (cmtype !== undefined) {
                localVarQueryParameter['cmtype'] = cmtype;
            }

            if (realm !== undefined) {
                localVarQueryParameter['realm'] = realm;
            }

            if (maxcount !== undefined) {
                localVarQueryParameter['maxcount'] = maxcount;
            }

            if (qoslevel !== undefined) {
                localVarQueryParameter['qoslevel'] = qoslevel;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} cellid Client\&#39;s Steam cell ID
         * @param {number} [maxcount] Max number of servers to return
         * @param {ISteamDirectoryGetCMListV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iSteamDirectoryGetCMListV1Get: async (cellid: number, maxcount?: number, format?: ISteamDirectoryGetCMListV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cellid' is not null or undefined
            assertParamExists('iSteamDirectoryGetCMListV1Get', 'cellid', cellid)
            const localVarPath = `/ISteamDirectory/GetCMList/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (cellid !== undefined) {
                localVarQueryParameter['cellid'] = cellid;
            }

            if (maxcount !== undefined) {
                localVarQueryParameter['maxcount'] = maxcount;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ISteamDirectoryGetSteamPipeDomainsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iSteamDirectoryGetSteamPipeDomainsV1Get: async (format?: ISteamDirectoryGetSteamPipeDomainsV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ISteamDirectory/GetSteamPipeDomains/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ISteamDirectoryApi - functional programming interface
 */
export const ISteamDirectoryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ISteamDirectoryApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} [cellid] Client\&#39;s Steam cell ID, uses IP location if blank
         * @param {string} [cmtype] Optional CM type filter
         * @param {string} [realm] Optional Steam Realm filter
         * @param {number} [maxcount] Max number of servers to return
         * @param {number} [qoslevel] Desired connection priority
         * @param {ISteamDirectoryGetCMListForConnectV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iSteamDirectoryGetCMListForConnectV1Get(cellid?: number, cmtype?: string, realm?: string, maxcount?: number, qoslevel?: number, format?: ISteamDirectoryGetCMListForConnectV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iSteamDirectoryGetCMListForConnectV1Get(cellid, cmtype, realm, maxcount, qoslevel, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ISteamDirectoryApi.iSteamDirectoryGetCMListForConnectV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} cellid Client\&#39;s Steam cell ID
         * @param {number} [maxcount] Max number of servers to return
         * @param {ISteamDirectoryGetCMListV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iSteamDirectoryGetCMListV1Get(cellid: number, maxcount?: number, format?: ISteamDirectoryGetCMListV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iSteamDirectoryGetCMListV1Get(cellid, maxcount, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ISteamDirectoryApi.iSteamDirectoryGetCMListV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {ISteamDirectoryGetSteamPipeDomainsV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iSteamDirectoryGetSteamPipeDomainsV1Get(format?: ISteamDirectoryGetSteamPipeDomainsV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iSteamDirectoryGetSteamPipeDomainsV1Get(format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ISteamDirectoryApi.iSteamDirectoryGetSteamPipeDomainsV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ISteamDirectoryApi - factory interface
 */
export const ISteamDirectoryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ISteamDirectoryApiFp(configuration)
    return {
        /**
         * 
         * @param {ISteamDirectoryApiISteamDirectoryGetCMListForConnectV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iSteamDirectoryGetCMListForConnectV1Get(requestParameters: ISteamDirectoryApiISteamDirectoryGetCMListForConnectV1GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iSteamDirectoryGetCMListForConnectV1Get(requestParameters.cellid, requestParameters.cmtype, requestParameters.realm, requestParameters.maxcount, requestParameters.qoslevel, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ISteamDirectoryApiISteamDirectoryGetCMListV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iSteamDirectoryGetCMListV1Get(requestParameters: ISteamDirectoryApiISteamDirectoryGetCMListV1GetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iSteamDirectoryGetCMListV1Get(requestParameters.cellid, requestParameters.maxcount, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ISteamDirectoryApiISteamDirectoryGetSteamPipeDomainsV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iSteamDirectoryGetSteamPipeDomainsV1Get(requestParameters: ISteamDirectoryApiISteamDirectoryGetSteamPipeDomainsV1GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iSteamDirectoryGetSteamPipeDomainsV1Get(requestParameters.format, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for iSteamDirectoryGetCMListForConnectV1Get operation in ISteamDirectoryApi.
 */
export interface ISteamDirectoryApiISteamDirectoryGetCMListForConnectV1GetRequest {
    /**
     * Client\&#39;s Steam cell ID, uses IP location if blank
     */
    readonly cellid?: number

    /**
     * Optional CM type filter
     */
    readonly cmtype?: string

    /**
     * Optional Steam Realm filter
     */
    readonly realm?: string

    /**
     * Max number of servers to return
     */
    readonly maxcount?: number

    /**
     * Desired connection priority
     */
    readonly qoslevel?: number

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: ISteamDirectoryGetCMListForConnectV1GetFormatEnum
}

/**
 * Request parameters for iSteamDirectoryGetCMListV1Get operation in ISteamDirectoryApi.
 */
export interface ISteamDirectoryApiISteamDirectoryGetCMListV1GetRequest {
    /**
     * Client\&#39;s Steam cell ID
     */
    readonly cellid: number

    /**
     * Max number of servers to return
     */
    readonly maxcount?: number

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: ISteamDirectoryGetCMListV1GetFormatEnum
}

/**
 * Request parameters for iSteamDirectoryGetSteamPipeDomainsV1Get operation in ISteamDirectoryApi.
 */
export interface ISteamDirectoryApiISteamDirectoryGetSteamPipeDomainsV1GetRequest {
    /**
     * The format of the response. Defaults to json
     */
    readonly format?: ISteamDirectoryGetSteamPipeDomainsV1GetFormatEnum
}

/**
 * ISteamDirectoryApi - object-oriented interface
 */
export class ISteamDirectoryApi extends BaseAPI {
    /**
     * 
     * @param {ISteamDirectoryApiISteamDirectoryGetCMListForConnectV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iSteamDirectoryGetCMListForConnectV1Get(requestParameters: ISteamDirectoryApiISteamDirectoryGetCMListForConnectV1GetRequest = {}, options?: RawAxiosRequestConfig) {
        return ISteamDirectoryApiFp(this.configuration).iSteamDirectoryGetCMListForConnectV1Get(requestParameters.cellid, requestParameters.cmtype, requestParameters.realm, requestParameters.maxcount, requestParameters.qoslevel, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ISteamDirectoryApiISteamDirectoryGetCMListV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iSteamDirectoryGetCMListV1Get(requestParameters: ISteamDirectoryApiISteamDirectoryGetCMListV1GetRequest, options?: RawAxiosRequestConfig) {
        return ISteamDirectoryApiFp(this.configuration).iSteamDirectoryGetCMListV1Get(requestParameters.cellid, requestParameters.maxcount, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ISteamDirectoryApiISteamDirectoryGetSteamPipeDomainsV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iSteamDirectoryGetSteamPipeDomainsV1Get(requestParameters: ISteamDirectoryApiISteamDirectoryGetSteamPipeDomainsV1GetRequest = {}, options?: RawAxiosRequestConfig) {
        return ISteamDirectoryApiFp(this.configuration).iSteamDirectoryGetSteamPipeDomainsV1Get(requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }
}

export const ISteamDirectoryGetCMListForConnectV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type ISteamDirectoryGetCMListForConnectV1GetFormatEnum = typeof ISteamDirectoryGetCMListForConnectV1GetFormatEnum[keyof typeof ISteamDirectoryGetCMListForConnectV1GetFormatEnum];
export const ISteamDirectoryGetCMListV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type ISteamDirectoryGetCMListV1GetFormatEnum = typeof ISteamDirectoryGetCMListV1GetFormatEnum[keyof typeof ISteamDirectoryGetCMListV1GetFormatEnum];
export const ISteamDirectoryGetSteamPipeDomainsV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type ISteamDirectoryGetSteamPipeDomainsV1GetFormatEnum = typeof ISteamDirectoryGetSteamPipeDomainsV1GetFormatEnum[keyof typeof ISteamDirectoryGetSteamPipeDomainsV1GetFormatEnum];
