/* tslint:disable */
/* eslint-disable */
/**
 * Steamworks Web API
 * This is an OpenAPI specification for the Steamworks Web API. For more details on how to use this tool, check out the <a href=\"https://github.com/ceva24/openapi-steamworks-web-api/blob/main/README.md\">README</a>.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * ISteamNewsApi - axios parameter creator
 */
export const ISteamNewsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} appid AppID to retrieve news for
         * @param {number} [maxlength] Maximum length for the content to return, if this is 0 the full content is returned, if it\&#39;s less then a blurb is generated to fit.
         * @param {number} [enddate] Retrieve posts earlier than this date (unix epoch timestamp)
         * @param {number} [count] # of posts to retrieve (default 20)
         * @param {string} [tags] Comma-separated list of tags to filter by (e.g. \&#39;patchnodes\&#39;)
         * @param {ISteamNewsGetNewsForAppV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iSteamNewsGetNewsForAppV1Get: async (appid: number, maxlength?: number, enddate?: number, count?: number, tags?: string, format?: ISteamNewsGetNewsForAppV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'appid' is not null or undefined
            assertParamExists('iSteamNewsGetNewsForAppV1Get', 'appid', appid)
            const localVarPath = `/ISteamNews/GetNewsForApp/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (appid !== undefined) {
                localVarQueryParameter['appid'] = appid;
            }

            if (maxlength !== undefined) {
                localVarQueryParameter['maxlength'] = maxlength;
            }

            if (enddate !== undefined) {
                localVarQueryParameter['enddate'] = enddate;
            }

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }

            if (tags !== undefined) {
                localVarQueryParameter['tags'] = tags;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} appid AppID to retrieve news for
         * @param {number} [maxlength] Maximum length for the content to return, if this is 0 the full content is returned, if it\&#39;s less then a blurb is generated to fit.
         * @param {number} [enddate] Retrieve posts earlier than this date (unix epoch timestamp)
         * @param {number} [count] # of posts to retrieve (default 20)
         * @param {string} [feeds] Comma-separated list of feed names to return news for
         * @param {string} [tags] Comma-separated list of tags to filter by (e.g. \&#39;patchnodes\&#39;)
         * @param {ISteamNewsGetNewsForAppV2GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iSteamNewsGetNewsForAppV2Get: async (appid: number, maxlength?: number, enddate?: number, count?: number, feeds?: string, tags?: string, format?: ISteamNewsGetNewsForAppV2GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'appid' is not null or undefined
            assertParamExists('iSteamNewsGetNewsForAppV2Get', 'appid', appid)
            const localVarPath = `/ISteamNews/GetNewsForApp/v2`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (appid !== undefined) {
                localVarQueryParameter['appid'] = appid;
            }

            if (maxlength !== undefined) {
                localVarQueryParameter['maxlength'] = maxlength;
            }

            if (enddate !== undefined) {
                localVarQueryParameter['enddate'] = enddate;
            }

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }

            if (feeds !== undefined) {
                localVarQueryParameter['feeds'] = feeds;
            }

            if (tags !== undefined) {
                localVarQueryParameter['tags'] = tags;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ISteamNewsApi - functional programming interface
 */
export const ISteamNewsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ISteamNewsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} appid AppID to retrieve news for
         * @param {number} [maxlength] Maximum length for the content to return, if this is 0 the full content is returned, if it\&#39;s less then a blurb is generated to fit.
         * @param {number} [enddate] Retrieve posts earlier than this date (unix epoch timestamp)
         * @param {number} [count] # of posts to retrieve (default 20)
         * @param {string} [tags] Comma-separated list of tags to filter by (e.g. \&#39;patchnodes\&#39;)
         * @param {ISteamNewsGetNewsForAppV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iSteamNewsGetNewsForAppV1Get(appid: number, maxlength?: number, enddate?: number, count?: number, tags?: string, format?: ISteamNewsGetNewsForAppV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iSteamNewsGetNewsForAppV1Get(appid, maxlength, enddate, count, tags, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ISteamNewsApi.iSteamNewsGetNewsForAppV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} appid AppID to retrieve news for
         * @param {number} [maxlength] Maximum length for the content to return, if this is 0 the full content is returned, if it\&#39;s less then a blurb is generated to fit.
         * @param {number} [enddate] Retrieve posts earlier than this date (unix epoch timestamp)
         * @param {number} [count] # of posts to retrieve (default 20)
         * @param {string} [feeds] Comma-separated list of feed names to return news for
         * @param {string} [tags] Comma-separated list of tags to filter by (e.g. \&#39;patchnodes\&#39;)
         * @param {ISteamNewsGetNewsForAppV2GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iSteamNewsGetNewsForAppV2Get(appid: number, maxlength?: number, enddate?: number, count?: number, feeds?: string, tags?: string, format?: ISteamNewsGetNewsForAppV2GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iSteamNewsGetNewsForAppV2Get(appid, maxlength, enddate, count, feeds, tags, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ISteamNewsApi.iSteamNewsGetNewsForAppV2Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ISteamNewsApi - factory interface
 */
export const ISteamNewsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ISteamNewsApiFp(configuration)
    return {
        /**
         * 
         * @param {ISteamNewsApiISteamNewsGetNewsForAppV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iSteamNewsGetNewsForAppV1Get(requestParameters: ISteamNewsApiISteamNewsGetNewsForAppV1GetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iSteamNewsGetNewsForAppV1Get(requestParameters.appid, requestParameters.maxlength, requestParameters.enddate, requestParameters.count, requestParameters.tags, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ISteamNewsApiISteamNewsGetNewsForAppV2GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iSteamNewsGetNewsForAppV2Get(requestParameters: ISteamNewsApiISteamNewsGetNewsForAppV2GetRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iSteamNewsGetNewsForAppV2Get(requestParameters.appid, requestParameters.maxlength, requestParameters.enddate, requestParameters.count, requestParameters.feeds, requestParameters.tags, requestParameters.format, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for iSteamNewsGetNewsForAppV1Get operation in ISteamNewsApi.
 */
export interface ISteamNewsApiISteamNewsGetNewsForAppV1GetRequest {
    /**
     * AppID to retrieve news for
     */
    readonly appid: number

    /**
     * Maximum length for the content to return, if this is 0 the full content is returned, if it\&#39;s less then a blurb is generated to fit.
     */
    readonly maxlength?: number

    /**
     * Retrieve posts earlier than this date (unix epoch timestamp)
     */
    readonly enddate?: number

    /**
     * # of posts to retrieve (default 20)
     */
    readonly count?: number

    /**
     * Comma-separated list of tags to filter by (e.g. \&#39;patchnodes\&#39;)
     */
    readonly tags?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: ISteamNewsGetNewsForAppV1GetFormatEnum
}

/**
 * Request parameters for iSteamNewsGetNewsForAppV2Get operation in ISteamNewsApi.
 */
export interface ISteamNewsApiISteamNewsGetNewsForAppV2GetRequest {
    /**
     * AppID to retrieve news for
     */
    readonly appid: number

    /**
     * Maximum length for the content to return, if this is 0 the full content is returned, if it\&#39;s less then a blurb is generated to fit.
     */
    readonly maxlength?: number

    /**
     * Retrieve posts earlier than this date (unix epoch timestamp)
     */
    readonly enddate?: number

    /**
     * # of posts to retrieve (default 20)
     */
    readonly count?: number

    /**
     * Comma-separated list of feed names to return news for
     */
    readonly feeds?: string

    /**
     * Comma-separated list of tags to filter by (e.g. \&#39;patchnodes\&#39;)
     */
    readonly tags?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: ISteamNewsGetNewsForAppV2GetFormatEnum
}

/**
 * ISteamNewsApi - object-oriented interface
 */
export class ISteamNewsApi extends BaseAPI {
    /**
     * 
     * @param {ISteamNewsApiISteamNewsGetNewsForAppV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iSteamNewsGetNewsForAppV1Get(requestParameters: ISteamNewsApiISteamNewsGetNewsForAppV1GetRequest, options?: RawAxiosRequestConfig) {
        return ISteamNewsApiFp(this.configuration).iSteamNewsGetNewsForAppV1Get(requestParameters.appid, requestParameters.maxlength, requestParameters.enddate, requestParameters.count, requestParameters.tags, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ISteamNewsApiISteamNewsGetNewsForAppV2GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iSteamNewsGetNewsForAppV2Get(requestParameters: ISteamNewsApiISteamNewsGetNewsForAppV2GetRequest, options?: RawAxiosRequestConfig) {
        return ISteamNewsApiFp(this.configuration).iSteamNewsGetNewsForAppV2Get(requestParameters.appid, requestParameters.maxlength, requestParameters.enddate, requestParameters.count, requestParameters.feeds, requestParameters.tags, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }
}

export const ISteamNewsGetNewsForAppV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type ISteamNewsGetNewsForAppV1GetFormatEnum = typeof ISteamNewsGetNewsForAppV1GetFormatEnum[keyof typeof ISteamNewsGetNewsForAppV1GetFormatEnum];
export const ISteamNewsGetNewsForAppV2GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type ISteamNewsGetNewsForAppV2GetFormatEnum = typeof ISteamNewsGetNewsForAppV2GetFormatEnum[keyof typeof ISteamNewsGetNewsForAppV2GetFormatEnum];
