/* tslint:disable */
/* eslint-disable */
/**
 * Steamworks Web API
 * This is an OpenAPI specification for the Steamworks Web API. For more details on how to use this tool, check out the <a href=\"https://github.com/ceva24/openapi-steamworks-web-api/blob/main/README.md\">README</a>.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * ISteamCDNApi - axios parameter creator
 */
export const ISteamCDNApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} cdnname Steam name of CDN property
         * @param {ISteamCDNSetClientFiltersV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {string} [allowedipblocks] comma-separated list of allowed IP address blocks in CIDR format - blank for not used
         * @param {string} [allowedasns] comma-separated list of allowed client network AS numbers - blank for not used
         * @param {string} [allowedipcountries] comma-separated list of allowed client IP country codes in ISO 3166-1 format - blank for not used
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iSteamCDNSetClientFiltersV1Post: async (cdnname: string, format?: ISteamCDNSetClientFiltersV1PostFormatEnum, allowedipblocks?: string, allowedasns?: string, allowedipcountries?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cdnname' is not null or undefined
            assertParamExists('iSteamCDNSetClientFiltersV1Post', 'cdnname', cdnname)
            const localVarPath = `/ISteamCDN/SetClientFilters/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            if (cdnname !== undefined) { 
                localVarFormParams.set('cdnname', cdnname as any);
            }

            if (allowedipblocks !== undefined) { 
                localVarFormParams.set('allowedipblocks', allowedipblocks as any);
            }

            if (allowedasns !== undefined) { 
                localVarFormParams.set('allowedasns', allowedasns as any);
            }

            if (allowedipcountries !== undefined) { 
                localVarFormParams.set('allowedipcountries', allowedipcountries as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} cdnname Steam name of CDN property
         * @param {ISteamCDNSetPerformanceStatsV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [mbpsSent] Outgoing network traffic in Mbps
         * @param {number} [mbpsRecv] Incoming network traffic in Mbps
         * @param {number} [cpuPercent] Percent CPU load
         * @param {number} [cacheHitPercent] Percent cache hits
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iSteamCDNSetPerformanceStatsV1Post: async (cdnname: string, format?: ISteamCDNSetPerformanceStatsV1PostFormatEnum, mbpsSent?: number, mbpsRecv?: number, cpuPercent?: number, cacheHitPercent?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cdnname' is not null or undefined
            assertParamExists('iSteamCDNSetPerformanceStatsV1Post', 'cdnname', cdnname)
            const localVarPath = `/ISteamCDN/SetPerformanceStats/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new URLSearchParams();

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            if (cdnname !== undefined) { 
                localVarFormParams.set('cdnname', cdnname as any);
            }

            if (mbpsSent !== undefined) { 
                localVarFormParams.set('mbps_sent', mbpsSent as any);
            }

            if (mbpsRecv !== undefined) { 
                localVarFormParams.set('mbps_recv', mbpsRecv as any);
            }

            if (cpuPercent !== undefined) { 
                localVarFormParams.set('cpu_percent', cpuPercent as any);
            }

            if (cacheHitPercent !== undefined) { 
                localVarFormParams.set('cache_hit_percent', cacheHitPercent as any);
            }
            localVarHeaderParameter['Content-Type'] = 'application/x-www-form-urlencoded';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams.toString();

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ISteamCDNApi - functional programming interface
 */
export const ISteamCDNApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ISteamCDNApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} cdnname Steam name of CDN property
         * @param {ISteamCDNSetClientFiltersV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {string} [allowedipblocks] comma-separated list of allowed IP address blocks in CIDR format - blank for not used
         * @param {string} [allowedasns] comma-separated list of allowed client network AS numbers - blank for not used
         * @param {string} [allowedipcountries] comma-separated list of allowed client IP country codes in ISO 3166-1 format - blank for not used
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iSteamCDNSetClientFiltersV1Post(cdnname: string, format?: ISteamCDNSetClientFiltersV1PostFormatEnum, allowedipblocks?: string, allowedasns?: string, allowedipcountries?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iSteamCDNSetClientFiltersV1Post(cdnname, format, allowedipblocks, allowedasns, allowedipcountries, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ISteamCDNApi.iSteamCDNSetClientFiltersV1Post']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} cdnname Steam name of CDN property
         * @param {ISteamCDNSetPerformanceStatsV1PostFormatEnum} [format] The format of the response. Defaults to json
         * @param {number} [mbpsSent] Outgoing network traffic in Mbps
         * @param {number} [mbpsRecv] Incoming network traffic in Mbps
         * @param {number} [cpuPercent] Percent CPU load
         * @param {number} [cacheHitPercent] Percent cache hits
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iSteamCDNSetPerformanceStatsV1Post(cdnname: string, format?: ISteamCDNSetPerformanceStatsV1PostFormatEnum, mbpsSent?: number, mbpsRecv?: number, cpuPercent?: number, cacheHitPercent?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iSteamCDNSetPerformanceStatsV1Post(cdnname, format, mbpsSent, mbpsRecv, cpuPercent, cacheHitPercent, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ISteamCDNApi.iSteamCDNSetPerformanceStatsV1Post']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ISteamCDNApi - factory interface
 */
export const ISteamCDNApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ISteamCDNApiFp(configuration)
    return {
        /**
         * 
         * @param {ISteamCDNApiISteamCDNSetClientFiltersV1PostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iSteamCDNSetClientFiltersV1Post(requestParameters: ISteamCDNApiISteamCDNSetClientFiltersV1PostRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iSteamCDNSetClientFiltersV1Post(requestParameters.cdnname, requestParameters.format, requestParameters.allowedipblocks, requestParameters.allowedasns, requestParameters.allowedipcountries, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ISteamCDNApiISteamCDNSetPerformanceStatsV1PostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iSteamCDNSetPerformanceStatsV1Post(requestParameters: ISteamCDNApiISteamCDNSetPerformanceStatsV1PostRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iSteamCDNSetPerformanceStatsV1Post(requestParameters.cdnname, requestParameters.format, requestParameters.mbpsSent, requestParameters.mbpsRecv, requestParameters.cpuPercent, requestParameters.cacheHitPercent, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for iSteamCDNSetClientFiltersV1Post operation in ISteamCDNApi.
 */
export interface ISteamCDNApiISteamCDNSetClientFiltersV1PostRequest {
    /**
     * Steam name of CDN property
     */
    readonly cdnname: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: ISteamCDNSetClientFiltersV1PostFormatEnum

    /**
     * comma-separated list of allowed IP address blocks in CIDR format - blank for not used
     */
    readonly allowedipblocks?: string

    /**
     * comma-separated list of allowed client network AS numbers - blank for not used
     */
    readonly allowedasns?: string

    /**
     * comma-separated list of allowed client IP country codes in ISO 3166-1 format - blank for not used
     */
    readonly allowedipcountries?: string
}

/**
 * Request parameters for iSteamCDNSetPerformanceStatsV1Post operation in ISteamCDNApi.
 */
export interface ISteamCDNApiISteamCDNSetPerformanceStatsV1PostRequest {
    /**
     * Steam name of CDN property
     */
    readonly cdnname: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: ISteamCDNSetPerformanceStatsV1PostFormatEnum

    /**
     * Outgoing network traffic in Mbps
     */
    readonly mbpsSent?: number

    /**
     * Incoming network traffic in Mbps
     */
    readonly mbpsRecv?: number

    /**
     * Percent CPU load
     */
    readonly cpuPercent?: number

    /**
     * Percent cache hits
     */
    readonly cacheHitPercent?: number
}

/**
 * ISteamCDNApi - object-oriented interface
 */
export class ISteamCDNApi extends BaseAPI {
    /**
     * 
     * @param {ISteamCDNApiISteamCDNSetClientFiltersV1PostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iSteamCDNSetClientFiltersV1Post(requestParameters: ISteamCDNApiISteamCDNSetClientFiltersV1PostRequest, options?: RawAxiosRequestConfig) {
        return ISteamCDNApiFp(this.configuration).iSteamCDNSetClientFiltersV1Post(requestParameters.cdnname, requestParameters.format, requestParameters.allowedipblocks, requestParameters.allowedasns, requestParameters.allowedipcountries, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {ISteamCDNApiISteamCDNSetPerformanceStatsV1PostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iSteamCDNSetPerformanceStatsV1Post(requestParameters: ISteamCDNApiISteamCDNSetPerformanceStatsV1PostRequest, options?: RawAxiosRequestConfig) {
        return ISteamCDNApiFp(this.configuration).iSteamCDNSetPerformanceStatsV1Post(requestParameters.cdnname, requestParameters.format, requestParameters.mbpsSent, requestParameters.mbpsRecv, requestParameters.cpuPercent, requestParameters.cacheHitPercent, options).then((request) => request(this.axios, this.basePath));
    }
}

export const ISteamCDNSetClientFiltersV1PostFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type ISteamCDNSetClientFiltersV1PostFormatEnum = typeof ISteamCDNSetClientFiltersV1PostFormatEnum[keyof typeof ISteamCDNSetClientFiltersV1PostFormatEnum];
export const ISteamCDNSetPerformanceStatsV1PostFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type ISteamCDNSetPerformanceStatsV1PostFormatEnum = typeof ISteamCDNSetPerformanceStatsV1PostFormatEnum[keyof typeof ISteamCDNSetPerformanceStatsV1PostFormatEnum];
