/* tslint:disable */
/* eslint-disable */
/**
 * Steamworks Web API
 * This is an OpenAPI specification for the Steamworks Web API. For more details on how to use this tool, check out the <a href=\"https://github.com/ceva24/openapi-steamworks-web-api/blob/main/README.md\">README</a>.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * IStoreServiceApi - axios parameter creator
 */
export const IStoreServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} [ifModifiedSince] Return only items that have been modified since this date.
         * @param {string} [haveDescriptionLanguage] Return only items that have a description in this language.
         * @param {boolean} [includeGames] Include games (defaults to enabled)
         * @param {boolean} [includeDlc] Include DLC
         * @param {boolean} [includeSoftware] Include software items
         * @param {boolean} [includeVideos] Include videos and series
         * @param {boolean} [includeHardware] Include hardware
         * @param {number} [lastAppid] For continuations, this is the last appid returned from the previous call.
         * @param {number} [maxResults] Number of results to return at a time.  Default 10k, max 50k.
         * @param {string} [inputJson] An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IStoreServiceGetAppListV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iStoreServiceGetAppListV1Get: async (ifModifiedSince?: number, haveDescriptionLanguage?: string, includeGames?: boolean, includeDlc?: boolean, includeSoftware?: boolean, includeVideos?: boolean, includeHardware?: boolean, lastAppid?: number, maxResults?: number, inputJson?: string, format?: IStoreServiceGetAppListV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IStoreService/GetAppList/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (ifModifiedSince !== undefined) {
                localVarQueryParameter['if_modified_since'] = ifModifiedSince;
            }

            if (haveDescriptionLanguage !== undefined) {
                localVarQueryParameter['have_description_language'] = haveDescriptionLanguage;
            }

            if (includeGames !== undefined) {
                localVarQueryParameter['include_games'] = includeGames;
            }

            if (includeDlc !== undefined) {
                localVarQueryParameter['include_dlc'] = includeDlc;
            }

            if (includeSoftware !== undefined) {
                localVarQueryParameter['include_software'] = includeSoftware;
            }

            if (includeVideos !== undefined) {
                localVarQueryParameter['include_videos'] = includeVideos;
            }

            if (includeHardware !== undefined) {
                localVarQueryParameter['include_hardware'] = includeHardware;
            }

            if (lastAppid !== undefined) {
                localVarQueryParameter['last_appid'] = lastAppid;
            }

            if (maxResults !== undefined) {
                localVarQueryParameter['max_results'] = maxResults;
            }

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [language] (Required)
         * @param {string} [countryCode] (Required)
         * @param {boolean} [favorRarerTags] (Required) Biases tags towards tags that are less common. e.g. Favor Zombies over Action if the user plays the same number of games with both tags.
         * @param {string} [inputJson] An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IStoreServiceGetRecommendedTagsForUserV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iStoreServiceGetRecommendedTagsForUserV1Get: async (language?: string, countryCode?: string, favorRarerTags?: boolean, inputJson?: string, format?: IStoreServiceGetRecommendedTagsForUserV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IStoreService/GetRecommendedTagsForUser/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (language !== undefined) {
                localVarQueryParameter['language'] = language;
            }

            if (countryCode !== undefined) {
                localVarQueryParameter['country_code'] = countryCode;
            }

            if (favorRarerTags !== undefined) {
                localVarQueryParameter['favor_rarer_tags'] = favorRarerTags;
            }

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IStoreServiceApi - functional programming interface
 */
export const IStoreServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IStoreServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} [ifModifiedSince] Return only items that have been modified since this date.
         * @param {string} [haveDescriptionLanguage] Return only items that have a description in this language.
         * @param {boolean} [includeGames] Include games (defaults to enabled)
         * @param {boolean} [includeDlc] Include DLC
         * @param {boolean} [includeSoftware] Include software items
         * @param {boolean} [includeVideos] Include videos and series
         * @param {boolean} [includeHardware] Include hardware
         * @param {number} [lastAppid] For continuations, this is the last appid returned from the previous call.
         * @param {number} [maxResults] Number of results to return at a time.  Default 10k, max 50k.
         * @param {string} [inputJson] An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IStoreServiceGetAppListV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iStoreServiceGetAppListV1Get(ifModifiedSince?: number, haveDescriptionLanguage?: string, includeGames?: boolean, includeDlc?: boolean, includeSoftware?: boolean, includeVideos?: boolean, includeHardware?: boolean, lastAppid?: number, maxResults?: number, inputJson?: string, format?: IStoreServiceGetAppListV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iStoreServiceGetAppListV1Get(ifModifiedSince, haveDescriptionLanguage, includeGames, includeDlc, includeSoftware, includeVideos, includeHardware, lastAppid, maxResults, inputJson, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IStoreServiceApi.iStoreServiceGetAppListV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [language] (Required)
         * @param {string} [countryCode] (Required)
         * @param {boolean} [favorRarerTags] (Required) Biases tags towards tags that are less common. e.g. Favor Zombies over Action if the user plays the same number of games with both tags.
         * @param {string} [inputJson] An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IStoreServiceGetRecommendedTagsForUserV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iStoreServiceGetRecommendedTagsForUserV1Get(language?: string, countryCode?: string, favorRarerTags?: boolean, inputJson?: string, format?: IStoreServiceGetRecommendedTagsForUserV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iStoreServiceGetRecommendedTagsForUserV1Get(language, countryCode, favorRarerTags, inputJson, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IStoreServiceApi.iStoreServiceGetRecommendedTagsForUserV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * IStoreServiceApi - factory interface
 */
export const IStoreServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IStoreServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {IStoreServiceApiIStoreServiceGetAppListV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iStoreServiceGetAppListV1Get(requestParameters: IStoreServiceApiIStoreServiceGetAppListV1GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iStoreServiceGetAppListV1Get(requestParameters.ifModifiedSince, requestParameters.haveDescriptionLanguage, requestParameters.includeGames, requestParameters.includeDlc, requestParameters.includeSoftware, requestParameters.includeVideos, requestParameters.includeHardware, requestParameters.lastAppid, requestParameters.maxResults, requestParameters.inputJson, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IStoreServiceApiIStoreServiceGetRecommendedTagsForUserV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iStoreServiceGetRecommendedTagsForUserV1Get(requestParameters: IStoreServiceApiIStoreServiceGetRecommendedTagsForUserV1GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iStoreServiceGetRecommendedTagsForUserV1Get(requestParameters.language, requestParameters.countryCode, requestParameters.favorRarerTags, requestParameters.inputJson, requestParameters.format, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for iStoreServiceGetAppListV1Get operation in IStoreServiceApi.
 */
export interface IStoreServiceApiIStoreServiceGetAppListV1GetRequest {
    /**
     * Return only items that have been modified since this date.
     */
    readonly ifModifiedSince?: number

    /**
     * Return only items that have a description in this language.
     */
    readonly haveDescriptionLanguage?: string

    /**
     * Include games (defaults to enabled)
     */
    readonly includeGames?: boolean

    /**
     * Include DLC
     */
    readonly includeDlc?: boolean

    /**
     * Include software items
     */
    readonly includeSoftware?: boolean

    /**
     * Include videos and series
     */
    readonly includeVideos?: boolean

    /**
     * Include hardware
     */
    readonly includeHardware?: boolean

    /**
     * For continuations, this is the last appid returned from the previous call.
     */
    readonly lastAppid?: number

    /**
     * Number of results to return at a time.  Default 10k, max 50k.
     */
    readonly maxResults?: number

    /**
     * An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IStoreServiceGetAppListV1GetFormatEnum
}

/**
 * Request parameters for iStoreServiceGetRecommendedTagsForUserV1Get operation in IStoreServiceApi.
 */
export interface IStoreServiceApiIStoreServiceGetRecommendedTagsForUserV1GetRequest {
    /**
     * (Required)
     */
    readonly language?: string

    /**
     * (Required)
     */
    readonly countryCode?: string

    /**
     * (Required) Biases tags towards tags that are less common. e.g. Favor Zombies over Action if the user plays the same number of games with both tags.
     */
    readonly favorRarerTags?: boolean

    /**
     * An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IStoreServiceGetRecommendedTagsForUserV1GetFormatEnum
}

/**
 * IStoreServiceApi - object-oriented interface
 */
export class IStoreServiceApi extends BaseAPI {
    /**
     * 
     * @param {IStoreServiceApiIStoreServiceGetAppListV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iStoreServiceGetAppListV1Get(requestParameters: IStoreServiceApiIStoreServiceGetAppListV1GetRequest = {}, options?: RawAxiosRequestConfig) {
        return IStoreServiceApiFp(this.configuration).iStoreServiceGetAppListV1Get(requestParameters.ifModifiedSince, requestParameters.haveDescriptionLanguage, requestParameters.includeGames, requestParameters.includeDlc, requestParameters.includeSoftware, requestParameters.includeVideos, requestParameters.includeHardware, requestParameters.lastAppid, requestParameters.maxResults, requestParameters.inputJson, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IStoreServiceApiIStoreServiceGetRecommendedTagsForUserV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iStoreServiceGetRecommendedTagsForUserV1Get(requestParameters: IStoreServiceApiIStoreServiceGetRecommendedTagsForUserV1GetRequest = {}, options?: RawAxiosRequestConfig) {
        return IStoreServiceApiFp(this.configuration).iStoreServiceGetRecommendedTagsForUserV1Get(requestParameters.language, requestParameters.countryCode, requestParameters.favorRarerTags, requestParameters.inputJson, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }
}

export const IStoreServiceGetAppListV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IStoreServiceGetAppListV1GetFormatEnum = typeof IStoreServiceGetAppListV1GetFormatEnum[keyof typeof IStoreServiceGetAppListV1GetFormatEnum];
export const IStoreServiceGetRecommendedTagsForUserV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IStoreServiceGetRecommendedTagsForUserV1GetFormatEnum = typeof IStoreServiceGetRecommendedTagsForUserV1GetFormatEnum[keyof typeof IStoreServiceGetRecommendedTagsForUserV1GetFormatEnum];
