/* tslint:disable */
/* eslint-disable */
/**
 * Steamworks Web API
 * This is an OpenAPI specification for the Steamworks Web API. For more details on how to use this tool, check out the <a href=\"https://github.com/ceva24/openapi-steamworks-web-api/blob/main/README.md\">README</a>.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * IWishlistServiceApi - axios parameter creator
 */
export const IWishlistServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} [steamid] (Required)
         * @param {string} [inputJson] An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IWishlistServiceGetWishlistItemCountV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iWishlistServiceGetWishlistItemCountV1Get: async (steamid?: number, inputJson?: string, format?: IWishlistServiceGetWishlistItemCountV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IWishlistService/GetWishlistItemCount/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (steamid !== undefined) {
                localVarQueryParameter['steamid'] = steamid;
            }

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [steamid] (Required)
         * @param {string} [context] (Required)
         * @param {string} [dataRequest] (Required) If passed, item data will be returned
         * @param {string} [sortOrder] 
         * @param {string} [filters] (Required)
         * @param {number} [startIndex] Data in this range will be filled in with StoreBrowse data
         * @param {number} [pageSize] 
         * @param {string} [inputJson] An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IWishlistServiceGetWishlistSortedFilteredV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iWishlistServiceGetWishlistSortedFilteredV1Get: async (steamid?: number, context?: string, dataRequest?: string, sortOrder?: string, filters?: string, startIndex?: number, pageSize?: number, inputJson?: string, format?: IWishlistServiceGetWishlistSortedFilteredV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IWishlistService/GetWishlistSortedFiltered/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (steamid !== undefined) {
                localVarQueryParameter['steamid'] = steamid;
            }

            if (context !== undefined) {
                localVarQueryParameter['context'] = context;
            }

            if (dataRequest !== undefined) {
                localVarQueryParameter['data_request'] = dataRequest;
            }

            if (sortOrder !== undefined) {
                localVarQueryParameter['sort_order'] = sortOrder;
            }

            if (filters !== undefined) {
                localVarQueryParameter['filters'] = filters;
            }

            if (startIndex !== undefined) {
                localVarQueryParameter['start_index'] = startIndex;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [steamid] (Required)
         * @param {string} [inputJson] An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IWishlistServiceGetWishlistV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iWishlistServiceGetWishlistV1Get: async (steamid?: number, inputJson?: string, format?: IWishlistServiceGetWishlistV1GetFormatEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/IWishlistService/GetWishlist/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication key required
            await setApiKeyToObject(localVarQueryParameter, "key", configuration)

            if (steamid !== undefined) {
                localVarQueryParameter['steamid'] = steamid;
            }

            if (inputJson !== undefined) {
                localVarQueryParameter['input_json'] = inputJson;
            }

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IWishlistServiceApi - functional programming interface
 */
export const IWishlistServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IWishlistServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} [steamid] (Required)
         * @param {string} [inputJson] An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IWishlistServiceGetWishlistItemCountV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iWishlistServiceGetWishlistItemCountV1Get(steamid?: number, inputJson?: string, format?: IWishlistServiceGetWishlistItemCountV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iWishlistServiceGetWishlistItemCountV1Get(steamid, inputJson, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IWishlistServiceApi.iWishlistServiceGetWishlistItemCountV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [steamid] (Required)
         * @param {string} [context] (Required)
         * @param {string} [dataRequest] (Required) If passed, item data will be returned
         * @param {string} [sortOrder] 
         * @param {string} [filters] (Required)
         * @param {number} [startIndex] Data in this range will be filled in with StoreBrowse data
         * @param {number} [pageSize] 
         * @param {string} [inputJson] An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IWishlistServiceGetWishlistSortedFilteredV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iWishlistServiceGetWishlistSortedFilteredV1Get(steamid?: number, context?: string, dataRequest?: string, sortOrder?: string, filters?: string, startIndex?: number, pageSize?: number, inputJson?: string, format?: IWishlistServiceGetWishlistSortedFilteredV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iWishlistServiceGetWishlistSortedFilteredV1Get(steamid, context, dataRequest, sortOrder, filters, startIndex, pageSize, inputJson, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IWishlistServiceApi.iWishlistServiceGetWishlistSortedFilteredV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} [steamid] (Required)
         * @param {string} [inputJson] An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
         * @param {IWishlistServiceGetWishlistV1GetFormatEnum} [format] The format of the response. Defaults to json
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async iWishlistServiceGetWishlistV1Get(steamid?: number, inputJson?: string, format?: IWishlistServiceGetWishlistV1GetFormatEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.iWishlistServiceGetWishlistV1Get(steamid, inputJson, format, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IWishlistServiceApi.iWishlistServiceGetWishlistV1Get']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * IWishlistServiceApi - factory interface
 */
export const IWishlistServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IWishlistServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {IWishlistServiceApiIWishlistServiceGetWishlistItemCountV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iWishlistServiceGetWishlistItemCountV1Get(requestParameters: IWishlistServiceApiIWishlistServiceGetWishlistItemCountV1GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iWishlistServiceGetWishlistItemCountV1Get(requestParameters.steamid, requestParameters.inputJson, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IWishlistServiceApiIWishlistServiceGetWishlistSortedFilteredV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iWishlistServiceGetWishlistSortedFilteredV1Get(requestParameters: IWishlistServiceApiIWishlistServiceGetWishlistSortedFilteredV1GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iWishlistServiceGetWishlistSortedFilteredV1Get(requestParameters.steamid, requestParameters.context, requestParameters.dataRequest, requestParameters.sortOrder, requestParameters.filters, requestParameters.startIndex, requestParameters.pageSize, requestParameters.inputJson, requestParameters.format, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IWishlistServiceApiIWishlistServiceGetWishlistV1GetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        iWishlistServiceGetWishlistV1Get(requestParameters: IWishlistServiceApiIWishlistServiceGetWishlistV1GetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.iWishlistServiceGetWishlistV1Get(requestParameters.steamid, requestParameters.inputJson, requestParameters.format, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for iWishlistServiceGetWishlistItemCountV1Get operation in IWishlistServiceApi.
 */
export interface IWishlistServiceApiIWishlistServiceGetWishlistItemCountV1GetRequest {
    /**
     * (Required)
     */
    readonly steamid?: number

    /**
     * An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IWishlistServiceGetWishlistItemCountV1GetFormatEnum
}

/**
 * Request parameters for iWishlistServiceGetWishlistSortedFilteredV1Get operation in IWishlistServiceApi.
 */
export interface IWishlistServiceApiIWishlistServiceGetWishlistSortedFilteredV1GetRequest {
    /**
     * (Required)
     */
    readonly steamid?: number

    /**
     * (Required)
     */
    readonly context?: string

    /**
     * (Required) If passed, item data will be returned
     */
    readonly dataRequest?: string

    /**
     * 
     */
    readonly sortOrder?: string

    /**
     * (Required)
     */
    readonly filters?: string

    /**
     * Data in this range will be filled in with StoreBrowse data
     */
    readonly startIndex?: number

    /**
     * 
     */
    readonly pageSize?: number

    /**
     * An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IWishlistServiceGetWishlistSortedFilteredV1GetFormatEnum
}

/**
 * Request parameters for iWishlistServiceGetWishlistV1Get operation in IWishlistServiceApi.
 */
export interface IWishlistServiceApiIWishlistServiceGetWishlistV1GetRequest {
    /**
     * (Required)
     */
    readonly steamid?: number

    /**
     * An alternative to the query string parameters; pass arguments as a URL-encoded JSON blob. The \&quot;key\&quot; and \&quot;format\&quot; fields should still be passed as separate parameters
     */
    readonly inputJson?: string

    /**
     * The format of the response. Defaults to json
     */
    readonly format?: IWishlistServiceGetWishlistV1GetFormatEnum
}

/**
 * IWishlistServiceApi - object-oriented interface
 */
export class IWishlistServiceApi extends BaseAPI {
    /**
     * 
     * @param {IWishlistServiceApiIWishlistServiceGetWishlistItemCountV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iWishlistServiceGetWishlistItemCountV1Get(requestParameters: IWishlistServiceApiIWishlistServiceGetWishlistItemCountV1GetRequest = {}, options?: RawAxiosRequestConfig) {
        return IWishlistServiceApiFp(this.configuration).iWishlistServiceGetWishlistItemCountV1Get(requestParameters.steamid, requestParameters.inputJson, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IWishlistServiceApiIWishlistServiceGetWishlistSortedFilteredV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iWishlistServiceGetWishlistSortedFilteredV1Get(requestParameters: IWishlistServiceApiIWishlistServiceGetWishlistSortedFilteredV1GetRequest = {}, options?: RawAxiosRequestConfig) {
        return IWishlistServiceApiFp(this.configuration).iWishlistServiceGetWishlistSortedFilteredV1Get(requestParameters.steamid, requestParameters.context, requestParameters.dataRequest, requestParameters.sortOrder, requestParameters.filters, requestParameters.startIndex, requestParameters.pageSize, requestParameters.inputJson, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IWishlistServiceApiIWishlistServiceGetWishlistV1GetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public iWishlistServiceGetWishlistV1Get(requestParameters: IWishlistServiceApiIWishlistServiceGetWishlistV1GetRequest = {}, options?: RawAxiosRequestConfig) {
        return IWishlistServiceApiFp(this.configuration).iWishlistServiceGetWishlistV1Get(requestParameters.steamid, requestParameters.inputJson, requestParameters.format, options).then((request) => request(this.axios, this.basePath));
    }
}

export const IWishlistServiceGetWishlistItemCountV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IWishlistServiceGetWishlistItemCountV1GetFormatEnum = typeof IWishlistServiceGetWishlistItemCountV1GetFormatEnum[keyof typeof IWishlistServiceGetWishlistItemCountV1GetFormatEnum];
export const IWishlistServiceGetWishlistSortedFilteredV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IWishlistServiceGetWishlistSortedFilteredV1GetFormatEnum = typeof IWishlistServiceGetWishlistSortedFilteredV1GetFormatEnum[keyof typeof IWishlistServiceGetWishlistSortedFilteredV1GetFormatEnum];
export const IWishlistServiceGetWishlistV1GetFormatEnum = {
    Json: 'json',
    Xml: 'xml',
    Vdf: 'vdf',
} as const;
export type IWishlistServiceGetWishlistV1GetFormatEnum = typeof IWishlistServiceGetWishlistV1GetFormatEnum[keyof typeof IWishlistServiceGetWishlistV1GetFormatEnum];
